// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "UnityMath.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GameMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GameMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameMessage_2eproto;
namespace GameMessage {
class GameSyncMessage;
struct GameSyncMessageDefaultTypeInternal;
extern GameSyncMessageDefaultTypeInternal _GameSyncMessage_default_instance_;
class PlayerSync;
struct PlayerSyncDefaultTypeInternal;
extern PlayerSyncDefaultTypeInternal _PlayerSync_default_instance_;
}  // namespace GameMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::GameMessage::GameSyncMessage* Arena::CreateMaybeMessage<::GameMessage::GameSyncMessage>(Arena*);
template<> ::GameMessage::PlayerSync* Arena::CreateMaybeMessage<::GameMessage::PlayerSync>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GameMessage {

// ===================================================================

class GameSyncMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.GameSyncMessage) */ {
 public:
  inline GameSyncMessage() : GameSyncMessage(nullptr) {}
  ~GameSyncMessage() override;
  explicit PROTOBUF_CONSTEXPR GameSyncMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameSyncMessage(const GameSyncMessage& from);
  GameSyncMessage(GameSyncMessage&& from) noexcept
    : GameSyncMessage() {
    *this = ::std::move(from);
  }

  inline GameSyncMessage& operator=(const GameSyncMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSyncMessage& operator=(GameSyncMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSyncMessage& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kPlayer = 1,
    CONTENT_NOT_SET = 0,
  };

  static inline const GameSyncMessage* internal_default_instance() {
    return reinterpret_cast<const GameSyncMessage*>(
               &_GameSyncMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameSyncMessage& a, GameSyncMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(GameSyncMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSyncMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSyncMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameSyncMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameSyncMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameSyncMessage& from) {
    GameSyncMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameSyncMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.GameSyncMessage";
  }
  protected:
  explicit GameSyncMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
  };
  // .GameMessage.PlayerSync player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::GameMessage::PlayerSync& player() const;
  PROTOBUF_NODISCARD ::GameMessage::PlayerSync* release_player();
  ::GameMessage::PlayerSync* mutable_player();
  void set_allocated_player(::GameMessage::PlayerSync* player);
  private:
  const ::GameMessage::PlayerSync& _internal_player() const;
  ::GameMessage::PlayerSync* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::GameMessage::PlayerSync* player);
  ::GameMessage::PlayerSync* unsafe_arena_release_player();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:GameMessage.GameSyncMessage)
 private:
  class _Internal;
  void set_has_player();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::GameMessage::PlayerSync* player_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerSync final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.PlayerSync) */ {
 public:
  inline PlayerSync() : PlayerSync(nullptr) {}
  ~PlayerSync() override;
  explicit PROTOBUF_CONSTEXPR PlayerSync(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerSync(const PlayerSync& from);
  PlayerSync(PlayerSync&& from) noexcept
    : PlayerSync() {
    *this = ::std::move(from);
  }

  inline PlayerSync& operator=(const PlayerSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSync& operator=(PlayerSync&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerSync& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerSync* internal_default_instance() {
    return reinterpret_cast<const PlayerSync*>(
               &_PlayerSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerSync& a, PlayerSync& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerSync* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSync* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerSync* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerSync>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerSync& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerSync& from) {
    PlayerSync::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerSync* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.PlayerSync";
  }
  protected:
  explicit PlayerSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMoveFieldNumber = 2,
    kClientIdFieldNumber = 1,
  };
  // .UnityMath.Vector3D move = 2;
  bool has_move() const;
  private:
  bool _internal_has_move() const;
  public:
  void clear_move();
  const ::UnityMath::Vector3D& move() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_move();
  ::UnityMath::Vector3D* mutable_move();
  void set_allocated_move(::UnityMath::Vector3D* move);
  private:
  const ::UnityMath::Vector3D& _internal_move() const;
  ::UnityMath::Vector3D* _internal_mutable_move();
  public:
  void unsafe_arena_set_allocated_move(
      ::UnityMath::Vector3D* move);
  ::UnityMath::Vector3D* unsafe_arena_release_move();

  // uint64 clientId = 1;
  void clear_clientid();
  uint64_t clientid() const;
  void set_clientid(uint64_t value);
  private:
  uint64_t _internal_clientid() const;
  void _internal_set_clientid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.PlayerSync)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::UnityMath::Vector3D* move_;
    uint64_t clientid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameSyncMessage

// .GameMessage.PlayerSync player = 1;
inline bool GameSyncMessage::_internal_has_player() const {
  return content_case() == kPlayer;
}
inline bool GameSyncMessage::has_player() const {
  return _internal_has_player();
}
inline void GameSyncMessage::set_has_player() {
  _impl_._oneof_case_[0] = kPlayer;
}
inline void GameSyncMessage::clear_player() {
  if (_internal_has_player()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.player_;
    }
    clear_has_content();
  }
}
inline ::GameMessage::PlayerSync* GameSyncMessage::release_player() {
  // @@protoc_insertion_point(field_release:GameMessage.GameSyncMessage.player)
  if (_internal_has_player()) {
    clear_has_content();
    ::GameMessage::PlayerSync* temp = _impl_.content_.player_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.player_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GameMessage::PlayerSync& GameSyncMessage::_internal_player() const {
  return _internal_has_player()
      ? *_impl_.content_.player_
      : reinterpret_cast< ::GameMessage::PlayerSync&>(::GameMessage::_PlayerSync_default_instance_);
}
inline const ::GameMessage::PlayerSync& GameSyncMessage::player() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSyncMessage.player)
  return _internal_player();
}
inline ::GameMessage::PlayerSync* GameSyncMessage::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_unsafe_arena_release:GameMessage.GameSyncMessage.player)
  if (_internal_has_player()) {
    clear_has_content();
    ::GameMessage::PlayerSync* temp = _impl_.content_.player_;
    _impl_.content_.player_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GameSyncMessage::unsafe_arena_set_allocated_player(::GameMessage::PlayerSync* player) {
  clear_content();
  if (player) {
    set_has_player();
    _impl_.content_.player_ = player;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.GameSyncMessage.player)
}
inline ::GameMessage::PlayerSync* GameSyncMessage::_internal_mutable_player() {
  if (!_internal_has_player()) {
    clear_content();
    set_has_player();
    _impl_.content_.player_ = CreateMaybeMessage< ::GameMessage::PlayerSync >(GetArenaForAllocation());
  }
  return _impl_.content_.player_;
}
inline ::GameMessage::PlayerSync* GameSyncMessage::mutable_player() {
  ::GameMessage::PlayerSync* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSyncMessage.player)
  return _msg;
}

inline bool GameSyncMessage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void GameSyncMessage::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline GameSyncMessage::ContentCase GameSyncMessage::content_case() const {
  return GameSyncMessage::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PlayerSync

// uint64 clientId = 1;
inline void PlayerSync::clear_clientid() {
  _impl_.clientid_ = uint64_t{0u};
}
inline uint64_t PlayerSync::_internal_clientid() const {
  return _impl_.clientid_;
}
inline uint64_t PlayerSync::clientid() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.clientId)
  return _internal_clientid();
}
inline void PlayerSync::_internal_set_clientid(uint64_t value) {
  
  _impl_.clientid_ = value;
}
inline void PlayerSync::set_clientid(uint64_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSync.clientId)
}

// .UnityMath.Vector3D move = 2;
inline bool PlayerSync::_internal_has_move() const {
  return this != internal_default_instance() && _impl_.move_ != nullptr;
}
inline bool PlayerSync::has_move() const {
  return _internal_has_move();
}
inline const ::UnityMath::Vector3D& PlayerSync::_internal_move() const {
  const ::UnityMath::Vector3D* p = _impl_.move_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& PlayerSync::move() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.move)
  return _internal_move();
}
inline void PlayerSync::unsafe_arena_set_allocated_move(
    ::UnityMath::Vector3D* move) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.move_);
  }
  _impl_.move_ = move;
  if (move) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.PlayerSync.move)
}
inline ::UnityMath::Vector3D* PlayerSync::release_move() {
  
  ::UnityMath::Vector3D* temp = _impl_.move_;
  _impl_.move_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSync::unsafe_arena_release_move() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSync.move)
  
  ::UnityMath::Vector3D* temp = _impl_.move_;
  _impl_.move_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSync::_internal_mutable_move() {
  
  if (_impl_.move_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.move_ = p;
  }
  return _impl_.move_;
}
inline ::UnityMath::Vector3D* PlayerSync::mutable_move() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_move();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSync.move)
  return _msg;
}
inline void PlayerSync::set_allocated_move(::UnityMath::Vector3D* move) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.move_);
  }
  if (move) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(move));
    if (message_arena != submessage_arena) {
      move = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, move, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.move_ = move;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSync.move)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto
