// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "UnityMath.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GameMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GameMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameMessage_2eproto;
namespace GameMessage {
class GameFrame;
struct GameFrameDefaultTypeInternal;
extern GameFrameDefaultTypeInternal _GameFrame_default_instance_;
class GameSnapshot;
struct GameSnapshotDefaultTypeInternal;
extern GameSnapshotDefaultTypeInternal _GameSnapshot_default_instance_;
class GameSnapshotMessage;
struct GameSnapshotMessageDefaultTypeInternal;
extern GameSnapshotMessageDefaultTypeInternal _GameSnapshotMessage_default_instance_;
class GameSyncMessage;
struct GameSyncMessageDefaultTypeInternal;
extern GameSyncMessageDefaultTypeInternal _GameSyncMessage_default_instance_;
class HeartBeat;
struct HeartBeatDefaultTypeInternal;
extern HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
class ObjectSnapshotSync;
struct ObjectSnapshotSyncDefaultTypeInternal;
extern ObjectSnapshotSyncDefaultTypeInternal _ObjectSnapshotSync_default_instance_;
class PlayerSnapshotSync;
struct PlayerSnapshotSyncDefaultTypeInternal;
extern PlayerSnapshotSyncDefaultTypeInternal _PlayerSnapshotSync_default_instance_;
class PlayerSync;
struct PlayerSyncDefaultTypeInternal;
extern PlayerSyncDefaultTypeInternal _PlayerSync_default_instance_;
}  // namespace GameMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::GameMessage::GameFrame* Arena::CreateMaybeMessage<::GameMessage::GameFrame>(Arena*);
template<> ::GameMessage::GameSnapshot* Arena::CreateMaybeMessage<::GameMessage::GameSnapshot>(Arena*);
template<> ::GameMessage::GameSnapshotMessage* Arena::CreateMaybeMessage<::GameMessage::GameSnapshotMessage>(Arena*);
template<> ::GameMessage::GameSyncMessage* Arena::CreateMaybeMessage<::GameMessage::GameSyncMessage>(Arena*);
template<> ::GameMessage::HeartBeat* Arena::CreateMaybeMessage<::GameMessage::HeartBeat>(Arena*);
template<> ::GameMessage::ObjectSnapshotSync* Arena::CreateMaybeMessage<::GameMessage::ObjectSnapshotSync>(Arena*);
template<> ::GameMessage::PlayerSnapshotSync* Arena::CreateMaybeMessage<::GameMessage::PlayerSnapshotSync>(Arena*);
template<> ::GameMessage::PlayerSync* Arena::CreateMaybeMessage<::GameMessage::PlayerSync>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GameMessage {

// ===================================================================

class GameSyncMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.GameSyncMessage) */ {
 public:
  inline GameSyncMessage() : GameSyncMessage(nullptr) {}
  ~GameSyncMessage() override;
  explicit PROTOBUF_CONSTEXPR GameSyncMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameSyncMessage(const GameSyncMessage& from);
  GameSyncMessage(GameSyncMessage&& from) noexcept
    : GameSyncMessage() {
    *this = ::std::move(from);
  }

  inline GameSyncMessage& operator=(const GameSyncMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSyncMessage& operator=(GameSyncMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSyncMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameSyncMessage* internal_default_instance() {
    return reinterpret_cast<const GameSyncMessage*>(
               &_GameSyncMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameSyncMessage& a, GameSyncMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(GameSyncMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSyncMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSyncMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameSyncMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameSyncMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameSyncMessage& from) {
    GameSyncMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameSyncMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.GameSyncMessage";
  }
  protected:
  explicit GameSyncMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 3,
    kFrameIdFieldNumber = 1,
    kTimeFieldNumber = 2,
  };
  // repeated .GameMessage.PlayerSync players = 3;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::GameMessage::PlayerSync* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >*
      mutable_players();
  private:
  const ::GameMessage::PlayerSync& _internal_players(int index) const;
  ::GameMessage::PlayerSync* _internal_add_players();
  public:
  const ::GameMessage::PlayerSync& players(int index) const;
  ::GameMessage::PlayerSync* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >&
      players() const;

  // uint64 frameId = 1;
  void clear_frameid();
  uint64_t frameid() const;
  void set_frameid(uint64_t value);
  private:
  uint64_t _internal_frameid() const;
  void _internal_set_frameid(uint64_t value);
  public:

  // uint64 time = 2;
  void clear_time();
  uint64_t time() const;
  void set_time(uint64_t value);
  private:
  uint64_t _internal_time() const;
  void _internal_set_time(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.GameSyncMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync > players_;
    uint64_t frameid_;
    uint64_t time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class GameSnapshotMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.GameSnapshotMessage) */ {
 public:
  inline GameSnapshotMessage() : GameSnapshotMessage(nullptr) {}
  ~GameSnapshotMessage() override;
  explicit PROTOBUF_CONSTEXPR GameSnapshotMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameSnapshotMessage(const GameSnapshotMessage& from);
  GameSnapshotMessage(GameSnapshotMessage&& from) noexcept
    : GameSnapshotMessage() {
    *this = ::std::move(from);
  }

  inline GameSnapshotMessage& operator=(const GameSnapshotMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSnapshotMessage& operator=(GameSnapshotMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSnapshotMessage& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kSnapshot = 3,
    kFrames = 4,
    CONTENT_NOT_SET = 0,
  };

  static inline const GameSnapshotMessage* internal_default_instance() {
    return reinterpret_cast<const GameSnapshotMessage*>(
               &_GameSnapshotMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GameSnapshotMessage& a, GameSnapshotMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(GameSnapshotMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSnapshotMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSnapshotMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameSnapshotMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameSnapshotMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameSnapshotMessage& from) {
    GameSnapshotMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameSnapshotMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.GameSnapshotMessage";
  }
  protected:
  explicit GameSnapshotMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSnapshotFieldNumber = 3,
    kFramesFieldNumber = 4,
  };
  // .GameMessage.GameSnapshot snapshot = 3;
  bool has_snapshot() const;
  private:
  bool _internal_has_snapshot() const;
  public:
  void clear_snapshot();
  const ::GameMessage::GameSnapshot& snapshot() const;
  PROTOBUF_NODISCARD ::GameMessage::GameSnapshot* release_snapshot();
  ::GameMessage::GameSnapshot* mutable_snapshot();
  void set_allocated_snapshot(::GameMessage::GameSnapshot* snapshot);
  private:
  const ::GameMessage::GameSnapshot& _internal_snapshot() const;
  ::GameMessage::GameSnapshot* _internal_mutable_snapshot();
  public:
  void unsafe_arena_set_allocated_snapshot(
      ::GameMessage::GameSnapshot* snapshot);
  ::GameMessage::GameSnapshot* unsafe_arena_release_snapshot();

  // .GameMessage.GameFrame frames = 4;
  bool has_frames() const;
  private:
  bool _internal_has_frames() const;
  public:
  void clear_frames();
  const ::GameMessage::GameFrame& frames() const;
  PROTOBUF_NODISCARD ::GameMessage::GameFrame* release_frames();
  ::GameMessage::GameFrame* mutable_frames();
  void set_allocated_frames(::GameMessage::GameFrame* frames);
  private:
  const ::GameMessage::GameFrame& _internal_frames() const;
  ::GameMessage::GameFrame* _internal_mutable_frames();
  public:
  void unsafe_arena_set_allocated_frames(
      ::GameMessage::GameFrame* frames);
  ::GameMessage::GameFrame* unsafe_arena_release_frames();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:GameMessage.GameSnapshotMessage)
 private:
  class _Internal;
  void set_has_snapshot();
  void set_has_frames();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::GameMessage::GameSnapshot* snapshot_;
      ::GameMessage::GameFrame* frames_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class GameSnapshot final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.GameSnapshot) */ {
 public:
  inline GameSnapshot() : GameSnapshot(nullptr) {}
  ~GameSnapshot() override;
  explicit PROTOBUF_CONSTEXPR GameSnapshot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameSnapshot(const GameSnapshot& from);
  GameSnapshot(GameSnapshot&& from) noexcept
    : GameSnapshot() {
    *this = ::std::move(from);
  }

  inline GameSnapshot& operator=(const GameSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSnapshot& operator=(GameSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSnapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameSnapshot* internal_default_instance() {
    return reinterpret_cast<const GameSnapshot*>(
               &_GameSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GameSnapshot& a, GameSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(GameSnapshot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameSnapshot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameSnapshot& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameSnapshot& from) {
    GameSnapshot::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameSnapshot* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.GameSnapshot";
  }
  protected:
  explicit GameSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerSSsFieldNumber = 3,
    kObjectSSsFieldNumber = 4,
    kFrameIdFieldNumber = 1,
  };
  // repeated .GameMessage.PlayerSnapshotSync playerSSs = 3;
  int playersss_size() const;
  private:
  int _internal_playersss_size() const;
  public:
  void clear_playersss();
  ::GameMessage::PlayerSnapshotSync* mutable_playersss(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSnapshotSync >*
      mutable_playersss();
  private:
  const ::GameMessage::PlayerSnapshotSync& _internal_playersss(int index) const;
  ::GameMessage::PlayerSnapshotSync* _internal_add_playersss();
  public:
  const ::GameMessage::PlayerSnapshotSync& playersss(int index) const;
  ::GameMessage::PlayerSnapshotSync* add_playersss();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSnapshotSync >&
      playersss() const;

  // repeated .GameMessage.ObjectSnapshotSync objectSSs = 4;
  int objectsss_size() const;
  private:
  int _internal_objectsss_size() const;
  public:
  void clear_objectsss();
  ::GameMessage::ObjectSnapshotSync* mutable_objectsss(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::ObjectSnapshotSync >*
      mutable_objectsss();
  private:
  const ::GameMessage::ObjectSnapshotSync& _internal_objectsss(int index) const;
  ::GameMessage::ObjectSnapshotSync* _internal_add_objectsss();
  public:
  const ::GameMessage::ObjectSnapshotSync& objectsss(int index) const;
  ::GameMessage::ObjectSnapshotSync* add_objectsss();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::ObjectSnapshotSync >&
      objectsss() const;

  // uint64 frameId = 1;
  void clear_frameid();
  uint64_t frameid() const;
  void set_frameid(uint64_t value);
  private:
  uint64_t _internal_frameid() const;
  void _internal_set_frameid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.GameSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSnapshotSync > playersss_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::ObjectSnapshotSync > objectsss_;
    uint64_t frameid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class GameFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.GameFrame) */ {
 public:
  inline GameFrame() : GameFrame(nullptr) {}
  ~GameFrame() override;
  explicit PROTOBUF_CONSTEXPR GameFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameFrame(const GameFrame& from);
  GameFrame(GameFrame&& from) noexcept
    : GameFrame() {
    *this = ::std::move(from);
  }

  inline GameFrame& operator=(const GameFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameFrame& operator=(GameFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameFrame* internal_default_instance() {
    return reinterpret_cast<const GameFrame*>(
               &_GameFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GameFrame& a, GameFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(GameFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameFrame& from) {
    GameFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.GameFrame";
  }
  protected:
  explicit GameFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 2,
    kFrameIdFieldNumber = 1,
  };
  // repeated .GameMessage.PlayerSync players = 2;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::GameMessage::PlayerSync* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >*
      mutable_players();
  private:
  const ::GameMessage::PlayerSync& _internal_players(int index) const;
  ::GameMessage::PlayerSync* _internal_add_players();
  public:
  const ::GameMessage::PlayerSync& players(int index) const;
  ::GameMessage::PlayerSync* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >&
      players() const;

  // uint64 frameId = 1;
  void clear_frameid();
  uint64_t frameid() const;
  void set_frameid(uint64_t value);
  private:
  uint64_t _internal_frameid() const;
  void _internal_set_frameid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.GameFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync > players_;
    uint64_t frameid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerSync final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.PlayerSync) */ {
 public:
  inline PlayerSync() : PlayerSync(nullptr) {}
  ~PlayerSync() override;
  explicit PROTOBUF_CONSTEXPR PlayerSync(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerSync(const PlayerSync& from);
  PlayerSync(PlayerSync&& from) noexcept
    : PlayerSync() {
    *this = ::std::move(from);
  }

  inline PlayerSync& operator=(const PlayerSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSync& operator=(PlayerSync&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerSync& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerSync* internal_default_instance() {
    return reinterpret_cast<const PlayerSync*>(
               &_PlayerSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PlayerSync& a, PlayerSync& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerSync* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSync* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerSync* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerSync>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerSync& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerSync& from) {
    PlayerSync::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerSync* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.PlayerSync";
  }
  protected:
  explicit PlayerSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 3,
    kInputMoveFieldNumber = 4,
    kFrameIdFieldNumber = 1,
    kTimeFieldNumber = 2,
  };
  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .UnityMath.Vector3D inputMove = 4;
  bool has_inputmove() const;
  private:
  bool _internal_has_inputmove() const;
  public:
  void clear_inputmove();
  const ::UnityMath::Vector3D& inputmove() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_inputmove();
  ::UnityMath::Vector3D* mutable_inputmove();
  void set_allocated_inputmove(::UnityMath::Vector3D* inputmove);
  private:
  const ::UnityMath::Vector3D& _internal_inputmove() const;
  ::UnityMath::Vector3D* _internal_mutable_inputmove();
  public:
  void unsafe_arena_set_allocated_inputmove(
      ::UnityMath::Vector3D* inputmove);
  ::UnityMath::Vector3D* unsafe_arena_release_inputmove();

  // uint64 frameId = 1;
  void clear_frameid();
  uint64_t frameid() const;
  void set_frameid(uint64_t value);
  private:
  uint64_t _internal_frameid() const;
  void _internal_set_frameid(uint64_t value);
  public:

  // uint64 time = 2;
  void clear_time();
  uint64_t time() const;
  void set_time(uint64_t value);
  private:
  uint64_t _internal_time() const;
  void _internal_set_time(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.PlayerSync)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::UnityMath::Vector3D* inputmove_;
    uint64_t frameid_;
    uint64_t time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerSnapshotSync final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.PlayerSnapshotSync) */ {
 public:
  inline PlayerSnapshotSync() : PlayerSnapshotSync(nullptr) {}
  ~PlayerSnapshotSync() override;
  explicit PROTOBUF_CONSTEXPR PlayerSnapshotSync(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerSnapshotSync(const PlayerSnapshotSync& from);
  PlayerSnapshotSync(PlayerSnapshotSync&& from) noexcept
    : PlayerSnapshotSync() {
    *this = ::std::move(from);
  }

  inline PlayerSnapshotSync& operator=(const PlayerSnapshotSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSnapshotSync& operator=(PlayerSnapshotSync&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerSnapshotSync& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerSnapshotSync* internal_default_instance() {
    return reinterpret_cast<const PlayerSnapshotSync*>(
               &_PlayerSnapshotSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PlayerSnapshotSync& a, PlayerSnapshotSync& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerSnapshotSync* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSnapshotSync* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerSnapshotSync* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerSnapshotSync>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerSnapshotSync& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerSnapshotSync& from) {
    PlayerSnapshotSync::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerSnapshotSync* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.PlayerSnapshotSync";
  }
  protected:
  explicit PlayerSnapshotSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPosFieldNumber = 3,
    kVelocityFieldNumber = 4,
    kFrameIdFieldNumber = 2,
    kLastFrameIdFieldNumber = 5,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .UnityMath.Vector3D pos = 3;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::UnityMath::Vector3D& pos() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_pos();
  ::UnityMath::Vector3D* mutable_pos();
  void set_allocated_pos(::UnityMath::Vector3D* pos);
  private:
  const ::UnityMath::Vector3D& _internal_pos() const;
  ::UnityMath::Vector3D* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::UnityMath::Vector3D* pos);
  ::UnityMath::Vector3D* unsafe_arena_release_pos();

  // .UnityMath.Vector3D velocity = 4;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::UnityMath::Vector3D& velocity() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_velocity();
  ::UnityMath::Vector3D* mutable_velocity();
  void set_allocated_velocity(::UnityMath::Vector3D* velocity);
  private:
  const ::UnityMath::Vector3D& _internal_velocity() const;
  ::UnityMath::Vector3D* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::UnityMath::Vector3D* velocity);
  ::UnityMath::Vector3D* unsafe_arena_release_velocity();

  // uint64 frameId = 2;
  void clear_frameid();
  uint64_t frameid() const;
  void set_frameid(uint64_t value);
  private:
  uint64_t _internal_frameid() const;
  void _internal_set_frameid(uint64_t value);
  public:

  // uint64 lastFrameId = 5;
  void clear_lastframeid();
  uint64_t lastframeid() const;
  void set_lastframeid(uint64_t value);
  private:
  uint64_t _internal_lastframeid() const;
  void _internal_set_lastframeid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.PlayerSnapshotSync)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::UnityMath::Vector3D* pos_;
    ::UnityMath::Vector3D* velocity_;
    uint64_t frameid_;
    uint64_t lastframeid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class ObjectSnapshotSync final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.ObjectSnapshotSync) */ {
 public:
  inline ObjectSnapshotSync() : ObjectSnapshotSync(nullptr) {}
  ~ObjectSnapshotSync() override;
  explicit PROTOBUF_CONSTEXPR ObjectSnapshotSync(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectSnapshotSync(const ObjectSnapshotSync& from);
  ObjectSnapshotSync(ObjectSnapshotSync&& from) noexcept
    : ObjectSnapshotSync() {
    *this = ::std::move(from);
  }

  inline ObjectSnapshotSync& operator=(const ObjectSnapshotSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectSnapshotSync& operator=(ObjectSnapshotSync&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectSnapshotSync& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectSnapshotSync* internal_default_instance() {
    return reinterpret_cast<const ObjectSnapshotSync*>(
               &_ObjectSnapshotSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ObjectSnapshotSync& a, ObjectSnapshotSync& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectSnapshotSync* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectSnapshotSync* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectSnapshotSync* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectSnapshotSync>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectSnapshotSync& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectSnapshotSync& from) {
    ObjectSnapshotSync::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectSnapshotSync* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.ObjectSnapshotSync";
  }
  protected:
  explicit ObjectSnapshotSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kObjectIdFieldNumber = 1,
  };
  // .UnityMath.Vector3D pos = 2;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::UnityMath::Vector3D& pos() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_pos();
  ::UnityMath::Vector3D* mutable_pos();
  void set_allocated_pos(::UnityMath::Vector3D* pos);
  private:
  const ::UnityMath::Vector3D& _internal_pos() const;
  ::UnityMath::Vector3D* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::UnityMath::Vector3D* pos);
  ::UnityMath::Vector3D* unsafe_arena_release_pos();

  // .UnityMath.Vector3D velocity = 3;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::UnityMath::Vector3D& velocity() const;
  PROTOBUF_NODISCARD ::UnityMath::Vector3D* release_velocity();
  ::UnityMath::Vector3D* mutable_velocity();
  void set_allocated_velocity(::UnityMath::Vector3D* velocity);
  private:
  const ::UnityMath::Vector3D& _internal_velocity() const;
  ::UnityMath::Vector3D* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::UnityMath::Vector3D* velocity);
  ::UnityMath::Vector3D* unsafe_arena_release_velocity();

  // uint64 objectId = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.ObjectSnapshotSync)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::UnityMath::Vector3D* pos_;
    ::UnityMath::Vector3D* velocity_;
    uint64_t objectid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// -------------------------------------------------------------------

class HeartBeat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.HeartBeat) */ {
 public:
  inline HeartBeat() : HeartBeat(nullptr) {}
  ~HeartBeat() override;
  explicit PROTOBUF_CONSTEXPR HeartBeat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeat(const HeartBeat& from);
  HeartBeat(HeartBeat&& from) noexcept
    : HeartBeat() {
    *this = ::std::move(from);
  }

  inline HeartBeat& operator=(const HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeat& operator=(HeartBeat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeat* internal_default_instance() {
    return reinterpret_cast<const HeartBeat*>(
               &_HeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(HeartBeat& a, HeartBeat& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeat& from) {
    HeartBeat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.HeartBeat";
  }
  protected:
  explicit HeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kTimeFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 time = 2;
  void clear_time();
  uint64_t time() const;
  void set_time(uint64_t value);
  private:
  uint64_t _internal_time() const;
  void _internal_set_time(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.HeartBeat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint64_t time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameSyncMessage

// uint64 frameId = 1;
inline void GameSyncMessage::clear_frameid() {
  _impl_.frameid_ = uint64_t{0u};
}
inline uint64_t GameSyncMessage::_internal_frameid() const {
  return _impl_.frameid_;
}
inline uint64_t GameSyncMessage::frameid() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSyncMessage.frameId)
  return _internal_frameid();
}
inline void GameSyncMessage::_internal_set_frameid(uint64_t value) {
  
  _impl_.frameid_ = value;
}
inline void GameSyncMessage::set_frameid(uint64_t value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:GameMessage.GameSyncMessage.frameId)
}

// uint64 time = 2;
inline void GameSyncMessage::clear_time() {
  _impl_.time_ = uint64_t{0u};
}
inline uint64_t GameSyncMessage::_internal_time() const {
  return _impl_.time_;
}
inline uint64_t GameSyncMessage::time() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSyncMessage.time)
  return _internal_time();
}
inline void GameSyncMessage::_internal_set_time(uint64_t value) {
  
  _impl_.time_ = value;
}
inline void GameSyncMessage::set_time(uint64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:GameMessage.GameSyncMessage.time)
}

// repeated .GameMessage.PlayerSync players = 3;
inline int GameSyncMessage::_internal_players_size() const {
  return _impl_.players_.size();
}
inline int GameSyncMessage::players_size() const {
  return _internal_players_size();
}
inline void GameSyncMessage::clear_players() {
  _impl_.players_.Clear();
}
inline ::GameMessage::PlayerSync* GameSyncMessage::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSyncMessage.players)
  return _impl_.players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >*
GameSyncMessage::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:GameMessage.GameSyncMessage.players)
  return &_impl_.players_;
}
inline const ::GameMessage::PlayerSync& GameSyncMessage::_internal_players(int index) const {
  return _impl_.players_.Get(index);
}
inline const ::GameMessage::PlayerSync& GameSyncMessage::players(int index) const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSyncMessage.players)
  return _internal_players(index);
}
inline ::GameMessage::PlayerSync* GameSyncMessage::_internal_add_players() {
  return _impl_.players_.Add();
}
inline ::GameMessage::PlayerSync* GameSyncMessage::add_players() {
  ::GameMessage::PlayerSync* _add = _internal_add_players();
  // @@protoc_insertion_point(field_add:GameMessage.GameSyncMessage.players)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >&
GameSyncMessage::players() const {
  // @@protoc_insertion_point(field_list:GameMessage.GameSyncMessage.players)
  return _impl_.players_;
}

// -------------------------------------------------------------------

// GameSnapshotMessage

// .GameMessage.GameSnapshot snapshot = 3;
inline bool GameSnapshotMessage::_internal_has_snapshot() const {
  return content_case() == kSnapshot;
}
inline bool GameSnapshotMessage::has_snapshot() const {
  return _internal_has_snapshot();
}
inline void GameSnapshotMessage::set_has_snapshot() {
  _impl_._oneof_case_[0] = kSnapshot;
}
inline void GameSnapshotMessage::clear_snapshot() {
  if (_internal_has_snapshot()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.snapshot_;
    }
    clear_has_content();
  }
}
inline ::GameMessage::GameSnapshot* GameSnapshotMessage::release_snapshot() {
  // @@protoc_insertion_point(field_release:GameMessage.GameSnapshotMessage.snapshot)
  if (_internal_has_snapshot()) {
    clear_has_content();
    ::GameMessage::GameSnapshot* temp = _impl_.content_.snapshot_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.snapshot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GameMessage::GameSnapshot& GameSnapshotMessage::_internal_snapshot() const {
  return _internal_has_snapshot()
      ? *_impl_.content_.snapshot_
      : reinterpret_cast< ::GameMessage::GameSnapshot&>(::GameMessage::_GameSnapshot_default_instance_);
}
inline const ::GameMessage::GameSnapshot& GameSnapshotMessage::snapshot() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSnapshotMessage.snapshot)
  return _internal_snapshot();
}
inline ::GameMessage::GameSnapshot* GameSnapshotMessage::unsafe_arena_release_snapshot() {
  // @@protoc_insertion_point(field_unsafe_arena_release:GameMessage.GameSnapshotMessage.snapshot)
  if (_internal_has_snapshot()) {
    clear_has_content();
    ::GameMessage::GameSnapshot* temp = _impl_.content_.snapshot_;
    _impl_.content_.snapshot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GameSnapshotMessage::unsafe_arena_set_allocated_snapshot(::GameMessage::GameSnapshot* snapshot) {
  clear_content();
  if (snapshot) {
    set_has_snapshot();
    _impl_.content_.snapshot_ = snapshot;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.GameSnapshotMessage.snapshot)
}
inline ::GameMessage::GameSnapshot* GameSnapshotMessage::_internal_mutable_snapshot() {
  if (!_internal_has_snapshot()) {
    clear_content();
    set_has_snapshot();
    _impl_.content_.snapshot_ = CreateMaybeMessage< ::GameMessage::GameSnapshot >(GetArenaForAllocation());
  }
  return _impl_.content_.snapshot_;
}
inline ::GameMessage::GameSnapshot* GameSnapshotMessage::mutable_snapshot() {
  ::GameMessage::GameSnapshot* _msg = _internal_mutable_snapshot();
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSnapshotMessage.snapshot)
  return _msg;
}

// .GameMessage.GameFrame frames = 4;
inline bool GameSnapshotMessage::_internal_has_frames() const {
  return content_case() == kFrames;
}
inline bool GameSnapshotMessage::has_frames() const {
  return _internal_has_frames();
}
inline void GameSnapshotMessage::set_has_frames() {
  _impl_._oneof_case_[0] = kFrames;
}
inline void GameSnapshotMessage::clear_frames() {
  if (_internal_has_frames()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.frames_;
    }
    clear_has_content();
  }
}
inline ::GameMessage::GameFrame* GameSnapshotMessage::release_frames() {
  // @@protoc_insertion_point(field_release:GameMessage.GameSnapshotMessage.frames)
  if (_internal_has_frames()) {
    clear_has_content();
    ::GameMessage::GameFrame* temp = _impl_.content_.frames_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.frames_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GameMessage::GameFrame& GameSnapshotMessage::_internal_frames() const {
  return _internal_has_frames()
      ? *_impl_.content_.frames_
      : reinterpret_cast< ::GameMessage::GameFrame&>(::GameMessage::_GameFrame_default_instance_);
}
inline const ::GameMessage::GameFrame& GameSnapshotMessage::frames() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSnapshotMessage.frames)
  return _internal_frames();
}
inline ::GameMessage::GameFrame* GameSnapshotMessage::unsafe_arena_release_frames() {
  // @@protoc_insertion_point(field_unsafe_arena_release:GameMessage.GameSnapshotMessage.frames)
  if (_internal_has_frames()) {
    clear_has_content();
    ::GameMessage::GameFrame* temp = _impl_.content_.frames_;
    _impl_.content_.frames_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GameSnapshotMessage::unsafe_arena_set_allocated_frames(::GameMessage::GameFrame* frames) {
  clear_content();
  if (frames) {
    set_has_frames();
    _impl_.content_.frames_ = frames;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.GameSnapshotMessage.frames)
}
inline ::GameMessage::GameFrame* GameSnapshotMessage::_internal_mutable_frames() {
  if (!_internal_has_frames()) {
    clear_content();
    set_has_frames();
    _impl_.content_.frames_ = CreateMaybeMessage< ::GameMessage::GameFrame >(GetArenaForAllocation());
  }
  return _impl_.content_.frames_;
}
inline ::GameMessage::GameFrame* GameSnapshotMessage::mutable_frames() {
  ::GameMessage::GameFrame* _msg = _internal_mutable_frames();
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSnapshotMessage.frames)
  return _msg;
}

inline bool GameSnapshotMessage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void GameSnapshotMessage::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline GameSnapshotMessage::ContentCase GameSnapshotMessage::content_case() const {
  return GameSnapshotMessage::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// GameSnapshot

// uint64 frameId = 1;
inline void GameSnapshot::clear_frameid() {
  _impl_.frameid_ = uint64_t{0u};
}
inline uint64_t GameSnapshot::_internal_frameid() const {
  return _impl_.frameid_;
}
inline uint64_t GameSnapshot::frameid() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSnapshot.frameId)
  return _internal_frameid();
}
inline void GameSnapshot::_internal_set_frameid(uint64_t value) {
  
  _impl_.frameid_ = value;
}
inline void GameSnapshot::set_frameid(uint64_t value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:GameMessage.GameSnapshot.frameId)
}

// repeated .GameMessage.PlayerSnapshotSync playerSSs = 3;
inline int GameSnapshot::_internal_playersss_size() const {
  return _impl_.playersss_.size();
}
inline int GameSnapshot::playersss_size() const {
  return _internal_playersss_size();
}
inline void GameSnapshot::clear_playersss() {
  _impl_.playersss_.Clear();
}
inline ::GameMessage::PlayerSnapshotSync* GameSnapshot::mutable_playersss(int index) {
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSnapshot.playerSSs)
  return _impl_.playersss_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSnapshotSync >*
GameSnapshot::mutable_playersss() {
  // @@protoc_insertion_point(field_mutable_list:GameMessage.GameSnapshot.playerSSs)
  return &_impl_.playersss_;
}
inline const ::GameMessage::PlayerSnapshotSync& GameSnapshot::_internal_playersss(int index) const {
  return _impl_.playersss_.Get(index);
}
inline const ::GameMessage::PlayerSnapshotSync& GameSnapshot::playersss(int index) const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSnapshot.playerSSs)
  return _internal_playersss(index);
}
inline ::GameMessage::PlayerSnapshotSync* GameSnapshot::_internal_add_playersss() {
  return _impl_.playersss_.Add();
}
inline ::GameMessage::PlayerSnapshotSync* GameSnapshot::add_playersss() {
  ::GameMessage::PlayerSnapshotSync* _add = _internal_add_playersss();
  // @@protoc_insertion_point(field_add:GameMessage.GameSnapshot.playerSSs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSnapshotSync >&
GameSnapshot::playersss() const {
  // @@protoc_insertion_point(field_list:GameMessage.GameSnapshot.playerSSs)
  return _impl_.playersss_;
}

// repeated .GameMessage.ObjectSnapshotSync objectSSs = 4;
inline int GameSnapshot::_internal_objectsss_size() const {
  return _impl_.objectsss_.size();
}
inline int GameSnapshot::objectsss_size() const {
  return _internal_objectsss_size();
}
inline void GameSnapshot::clear_objectsss() {
  _impl_.objectsss_.Clear();
}
inline ::GameMessage::ObjectSnapshotSync* GameSnapshot::mutable_objectsss(int index) {
  // @@protoc_insertion_point(field_mutable:GameMessage.GameSnapshot.objectSSs)
  return _impl_.objectsss_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::ObjectSnapshotSync >*
GameSnapshot::mutable_objectsss() {
  // @@protoc_insertion_point(field_mutable_list:GameMessage.GameSnapshot.objectSSs)
  return &_impl_.objectsss_;
}
inline const ::GameMessage::ObjectSnapshotSync& GameSnapshot::_internal_objectsss(int index) const {
  return _impl_.objectsss_.Get(index);
}
inline const ::GameMessage::ObjectSnapshotSync& GameSnapshot::objectsss(int index) const {
  // @@protoc_insertion_point(field_get:GameMessage.GameSnapshot.objectSSs)
  return _internal_objectsss(index);
}
inline ::GameMessage::ObjectSnapshotSync* GameSnapshot::_internal_add_objectsss() {
  return _impl_.objectsss_.Add();
}
inline ::GameMessage::ObjectSnapshotSync* GameSnapshot::add_objectsss() {
  ::GameMessage::ObjectSnapshotSync* _add = _internal_add_objectsss();
  // @@protoc_insertion_point(field_add:GameMessage.GameSnapshot.objectSSs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::ObjectSnapshotSync >&
GameSnapshot::objectsss() const {
  // @@protoc_insertion_point(field_list:GameMessage.GameSnapshot.objectSSs)
  return _impl_.objectsss_;
}

// -------------------------------------------------------------------

// GameFrame

// uint64 frameId = 1;
inline void GameFrame::clear_frameid() {
  _impl_.frameid_ = uint64_t{0u};
}
inline uint64_t GameFrame::_internal_frameid() const {
  return _impl_.frameid_;
}
inline uint64_t GameFrame::frameid() const {
  // @@protoc_insertion_point(field_get:GameMessage.GameFrame.frameId)
  return _internal_frameid();
}
inline void GameFrame::_internal_set_frameid(uint64_t value) {
  
  _impl_.frameid_ = value;
}
inline void GameFrame::set_frameid(uint64_t value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:GameMessage.GameFrame.frameId)
}

// repeated .GameMessage.PlayerSync players = 2;
inline int GameFrame::_internal_players_size() const {
  return _impl_.players_.size();
}
inline int GameFrame::players_size() const {
  return _internal_players_size();
}
inline void GameFrame::clear_players() {
  _impl_.players_.Clear();
}
inline ::GameMessage::PlayerSync* GameFrame::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:GameMessage.GameFrame.players)
  return _impl_.players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >*
GameFrame::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:GameMessage.GameFrame.players)
  return &_impl_.players_;
}
inline const ::GameMessage::PlayerSync& GameFrame::_internal_players(int index) const {
  return _impl_.players_.Get(index);
}
inline const ::GameMessage::PlayerSync& GameFrame::players(int index) const {
  // @@protoc_insertion_point(field_get:GameMessage.GameFrame.players)
  return _internal_players(index);
}
inline ::GameMessage::PlayerSync* GameFrame::_internal_add_players() {
  return _impl_.players_.Add();
}
inline ::GameMessage::PlayerSync* GameFrame::add_players() {
  ::GameMessage::PlayerSync* _add = _internal_add_players();
  // @@protoc_insertion_point(field_add:GameMessage.GameFrame.players)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GameMessage::PlayerSync >&
GameFrame::players() const {
  // @@protoc_insertion_point(field_list:GameMessage.GameFrame.players)
  return _impl_.players_;
}

// -------------------------------------------------------------------

// PlayerSync

// uint64 frameId = 1;
inline void PlayerSync::clear_frameid() {
  _impl_.frameid_ = uint64_t{0u};
}
inline uint64_t PlayerSync::_internal_frameid() const {
  return _impl_.frameid_;
}
inline uint64_t PlayerSync::frameid() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.frameId)
  return _internal_frameid();
}
inline void PlayerSync::_internal_set_frameid(uint64_t value) {
  
  _impl_.frameid_ = value;
}
inline void PlayerSync::set_frameid(uint64_t value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSync.frameId)
}

// uint64 time = 2;
inline void PlayerSync::clear_time() {
  _impl_.time_ = uint64_t{0u};
}
inline uint64_t PlayerSync::_internal_time() const {
  return _impl_.time_;
}
inline uint64_t PlayerSync::time() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.time)
  return _internal_time();
}
inline void PlayerSync::_internal_set_time(uint64_t value) {
  
  _impl_.time_ = value;
}
inline void PlayerSync::set_time(uint64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSync.time)
}

// string name = 3;
inline void PlayerSync::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PlayerSync::name() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerSync::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSync.name)
}
inline std::string* PlayerSync::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSync.name)
  return _s;
}
inline const std::string& PlayerSync::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PlayerSync::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerSync::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerSync::release_name() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSync.name)
  return _impl_.name_.Release();
}
inline void PlayerSync::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSync.name)
}

// .UnityMath.Vector3D inputMove = 4;
inline bool PlayerSync::_internal_has_inputmove() const {
  return this != internal_default_instance() && _impl_.inputmove_ != nullptr;
}
inline bool PlayerSync::has_inputmove() const {
  return _internal_has_inputmove();
}
inline const ::UnityMath::Vector3D& PlayerSync::_internal_inputmove() const {
  const ::UnityMath::Vector3D* p = _impl_.inputmove_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& PlayerSync::inputmove() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSync.inputMove)
  return _internal_inputmove();
}
inline void PlayerSync::unsafe_arena_set_allocated_inputmove(
    ::UnityMath::Vector3D* inputmove) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inputmove_);
  }
  _impl_.inputmove_ = inputmove;
  if (inputmove) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.PlayerSync.inputMove)
}
inline ::UnityMath::Vector3D* PlayerSync::release_inputmove() {
  
  ::UnityMath::Vector3D* temp = _impl_.inputmove_;
  _impl_.inputmove_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSync::unsafe_arena_release_inputmove() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSync.inputMove)
  
  ::UnityMath::Vector3D* temp = _impl_.inputmove_;
  _impl_.inputmove_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSync::_internal_mutable_inputmove() {
  
  if (_impl_.inputmove_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.inputmove_ = p;
  }
  return _impl_.inputmove_;
}
inline ::UnityMath::Vector3D* PlayerSync::mutable_inputmove() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_inputmove();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSync.inputMove)
  return _msg;
}
inline void PlayerSync::set_allocated_inputmove(::UnityMath::Vector3D* inputmove) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inputmove_);
  }
  if (inputmove) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(inputmove));
    if (message_arena != submessage_arena) {
      inputmove = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, inputmove, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.inputmove_ = inputmove;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSync.inputMove)
}

// -------------------------------------------------------------------

// PlayerSnapshotSync

// string name = 1;
inline void PlayerSnapshotSync::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PlayerSnapshotSync::name() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSnapshotSync.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerSnapshotSync::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSnapshotSync.name)
}
inline std::string* PlayerSnapshotSync::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSnapshotSync.name)
  return _s;
}
inline const std::string& PlayerSnapshotSync::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PlayerSnapshotSync::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerSnapshotSync::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerSnapshotSync::release_name() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSnapshotSync.name)
  return _impl_.name_.Release();
}
inline void PlayerSnapshotSync::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSnapshotSync.name)
}

// uint64 frameId = 2;
inline void PlayerSnapshotSync::clear_frameid() {
  _impl_.frameid_ = uint64_t{0u};
}
inline uint64_t PlayerSnapshotSync::_internal_frameid() const {
  return _impl_.frameid_;
}
inline uint64_t PlayerSnapshotSync::frameid() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSnapshotSync.frameId)
  return _internal_frameid();
}
inline void PlayerSnapshotSync::_internal_set_frameid(uint64_t value) {
  
  _impl_.frameid_ = value;
}
inline void PlayerSnapshotSync::set_frameid(uint64_t value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSnapshotSync.frameId)
}

// uint64 lastFrameId = 5;
inline void PlayerSnapshotSync::clear_lastframeid() {
  _impl_.lastframeid_ = uint64_t{0u};
}
inline uint64_t PlayerSnapshotSync::_internal_lastframeid() const {
  return _impl_.lastframeid_;
}
inline uint64_t PlayerSnapshotSync::lastframeid() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSnapshotSync.lastFrameId)
  return _internal_lastframeid();
}
inline void PlayerSnapshotSync::_internal_set_lastframeid(uint64_t value) {
  
  _impl_.lastframeid_ = value;
}
inline void PlayerSnapshotSync::set_lastframeid(uint64_t value) {
  _internal_set_lastframeid(value);
  // @@protoc_insertion_point(field_set:GameMessage.PlayerSnapshotSync.lastFrameId)
}

// .UnityMath.Vector3D pos = 3;
inline bool PlayerSnapshotSync::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool PlayerSnapshotSync::has_pos() const {
  return _internal_has_pos();
}
inline const ::UnityMath::Vector3D& PlayerSnapshotSync::_internal_pos() const {
  const ::UnityMath::Vector3D* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& PlayerSnapshotSync::pos() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSnapshotSync.pos)
  return _internal_pos();
}
inline void PlayerSnapshotSync::unsafe_arena_set_allocated_pos(
    ::UnityMath::Vector3D* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.PlayerSnapshotSync.pos)
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::release_pos() {
  
  ::UnityMath::Vector3D* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSnapshotSync.pos)
  
  ::UnityMath::Vector3D* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::mutable_pos() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSnapshotSync.pos)
  return _msg;
}
inline void PlayerSnapshotSync::set_allocated_pos(::UnityMath::Vector3D* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos));
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSnapshotSync.pos)
}

// .UnityMath.Vector3D velocity = 4;
inline bool PlayerSnapshotSync::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool PlayerSnapshotSync::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::UnityMath::Vector3D& PlayerSnapshotSync::_internal_velocity() const {
  const ::UnityMath::Vector3D* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& PlayerSnapshotSync::velocity() const {
  // @@protoc_insertion_point(field_get:GameMessage.PlayerSnapshotSync.velocity)
  return _internal_velocity();
}
inline void PlayerSnapshotSync::unsafe_arena_set_allocated_velocity(
    ::UnityMath::Vector3D* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.PlayerSnapshotSync.velocity)
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::release_velocity() {
  
  ::UnityMath::Vector3D* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:GameMessage.PlayerSnapshotSync.velocity)
  
  ::UnityMath::Vector3D* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::UnityMath::Vector3D* PlayerSnapshotSync::mutable_velocity() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:GameMessage.PlayerSnapshotSync.velocity)
  return _msg;
}
inline void PlayerSnapshotSync::set_allocated_velocity(::UnityMath::Vector3D* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.PlayerSnapshotSync.velocity)
}

// -------------------------------------------------------------------

// ObjectSnapshotSync

// uint64 objectId = 1;
inline void ObjectSnapshotSync::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t ObjectSnapshotSync::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t ObjectSnapshotSync::objectid() const {
  // @@protoc_insertion_point(field_get:GameMessage.ObjectSnapshotSync.objectId)
  return _internal_objectid();
}
inline void ObjectSnapshotSync::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void ObjectSnapshotSync::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:GameMessage.ObjectSnapshotSync.objectId)
}

// .UnityMath.Vector3D pos = 2;
inline bool ObjectSnapshotSync::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool ObjectSnapshotSync::has_pos() const {
  return _internal_has_pos();
}
inline const ::UnityMath::Vector3D& ObjectSnapshotSync::_internal_pos() const {
  const ::UnityMath::Vector3D* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& ObjectSnapshotSync::pos() const {
  // @@protoc_insertion_point(field_get:GameMessage.ObjectSnapshotSync.pos)
  return _internal_pos();
}
inline void ObjectSnapshotSync::unsafe_arena_set_allocated_pos(
    ::UnityMath::Vector3D* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.ObjectSnapshotSync.pos)
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::release_pos() {
  
  ::UnityMath::Vector3D* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:GameMessage.ObjectSnapshotSync.pos)
  
  ::UnityMath::Vector3D* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::mutable_pos() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:GameMessage.ObjectSnapshotSync.pos)
  return _msg;
}
inline void ObjectSnapshotSync::set_allocated_pos(::UnityMath::Vector3D* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos));
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.ObjectSnapshotSync.pos)
}

// .UnityMath.Vector3D velocity = 3;
inline bool ObjectSnapshotSync::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool ObjectSnapshotSync::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::UnityMath::Vector3D& ObjectSnapshotSync::_internal_velocity() const {
  const ::UnityMath::Vector3D* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::UnityMath::Vector3D&>(
      ::UnityMath::_Vector3D_default_instance_);
}
inline const ::UnityMath::Vector3D& ObjectSnapshotSync::velocity() const {
  // @@protoc_insertion_point(field_get:GameMessage.ObjectSnapshotSync.velocity)
  return _internal_velocity();
}
inline void ObjectSnapshotSync::unsafe_arena_set_allocated_velocity(
    ::UnityMath::Vector3D* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.ObjectSnapshotSync.velocity)
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::release_velocity() {
  
  ::UnityMath::Vector3D* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:GameMessage.ObjectSnapshotSync.velocity)
  
  ::UnityMath::Vector3D* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::UnityMath::Vector3D>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::UnityMath::Vector3D* ObjectSnapshotSync::mutable_velocity() {
  ::UnityMath::Vector3D* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:GameMessage.ObjectSnapshotSync.velocity)
  return _msg;
}
inline void ObjectSnapshotSync::set_allocated_velocity(::UnityMath::Vector3D* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.ObjectSnapshotSync.velocity)
}

// -------------------------------------------------------------------

// HeartBeat

// string name = 1;
inline void HeartBeat::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& HeartBeat::name() const {
  // @@protoc_insertion_point(field_get:GameMessage.HeartBeat.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HeartBeat::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:GameMessage.HeartBeat.name)
}
inline std::string* HeartBeat::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:GameMessage.HeartBeat.name)
  return _s;
}
inline const std::string& HeartBeat::_internal_name() const {
  return _impl_.name_.Get();
}
inline void HeartBeat::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* HeartBeat::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* HeartBeat::release_name() {
  // @@protoc_insertion_point(field_release:GameMessage.HeartBeat.name)
  return _impl_.name_.Release();
}
inline void HeartBeat::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GameMessage.HeartBeat.name)
}

// uint64 time = 2;
inline void HeartBeat::clear_time() {
  _impl_.time_ = uint64_t{0u};
}
inline uint64_t HeartBeat::_internal_time() const {
  return _impl_.time_;
}
inline uint64_t HeartBeat::time() const {
  // @@protoc_insertion_point(field_get:GameMessage.HeartBeat.time)
  return _internal_time();
}
inline void HeartBeat::_internal_set_time(uint64_t value) {
  
  _impl_.time_ = value;
}
inline void HeartBeat::set_time(uint64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:GameMessage.HeartBeat.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GameMessage_2eproto
