// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMessage.proto

#include "GameMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GameMessage {
PROTOBUF_CONSTEXPR GameSyncMessage::GameSyncMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.players_)*/{}
  , /*decltype(_impl_.frameid_)*/uint64_t{0u}
  , /*decltype(_impl_.time_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameSyncMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameSyncMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameSyncMessageDefaultTypeInternal() {}
  union {
    GameSyncMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameSyncMessageDefaultTypeInternal _GameSyncMessage_default_instance_;
PROTOBUF_CONSTEXPR GameSnapshotMessage::GameSnapshotMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playersss_)*/{}
  , /*decltype(_impl_.objectsss_)*/{}
  , /*decltype(_impl_.frameid_)*/uint64_t{0u}
  , /*decltype(_impl_.lastframeid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameSnapshotMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameSnapshotMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameSnapshotMessageDefaultTypeInternal() {}
  union {
    GameSnapshotMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameSnapshotMessageDefaultTypeInternal _GameSnapshotMessage_default_instance_;
PROTOBUF_CONSTEXPR PlayerSync::PlayerSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.inputmove_)*/nullptr
  , /*decltype(_impl_.frameid_)*/uint64_t{0u}
  , /*decltype(_impl_.time_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerSyncDefaultTypeInternal() {}
  union {
    PlayerSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerSyncDefaultTypeInternal _PlayerSync_default_instance_;
PROTOBUF_CONSTEXPR PlayerSnapshotSync::PlayerSnapshotSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.pos_)*/nullptr
  , /*decltype(_impl_.velocity_)*/nullptr
  , /*decltype(_impl_.frameid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerSnapshotSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerSnapshotSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerSnapshotSyncDefaultTypeInternal() {}
  union {
    PlayerSnapshotSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerSnapshotSyncDefaultTypeInternal _PlayerSnapshotSync_default_instance_;
PROTOBUF_CONSTEXPR ObjectSnapshotSync::ObjectSnapshotSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pos_)*/nullptr
  , /*decltype(_impl_.velocity_)*/nullptr
  , /*decltype(_impl_.objectid_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ObjectSnapshotSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObjectSnapshotSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObjectSnapshotSyncDefaultTypeInternal() {}
  union {
    ObjectSnapshotSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObjectSnapshotSyncDefaultTypeInternal _ObjectSnapshotSync_default_instance_;
PROTOBUF_CONSTEXPR HeartBeat::HeartBeat(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatDefaultTypeInternal() {}
  union {
    HeartBeat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
}  // namespace GameMessage
static ::_pb::Metadata file_level_metadata_GameMessage_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_GameMessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_GameMessage_2eproto = nullptr;

const uint32_t TableStruct_GameMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSyncMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSyncMessage, _impl_.frameid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSyncMessage, _impl_.time_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSyncMessage, _impl_.players_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSnapshotMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSnapshotMessage, _impl_.frameid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSnapshotMessage, _impl_.lastframeid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSnapshotMessage, _impl_.playersss_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::GameSnapshotMessage, _impl_.objectsss_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSync, _impl_.frameid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSync, _impl_.time_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSync, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSync, _impl_.inputmove_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSnapshotSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSnapshotSync, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSnapshotSync, _impl_.frameid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSnapshotSync, _impl_.pos_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::PlayerSnapshotSync, _impl_.velocity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::ObjectSnapshotSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::ObjectSnapshotSync, _impl_.objectid_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::ObjectSnapshotSync, _impl_.pos_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::ObjectSnapshotSync, _impl_.velocity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GameMessage::HeartBeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GameMessage::HeartBeat, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::GameMessage::HeartBeat, _impl_.time_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GameMessage::GameSyncMessage)},
  { 9, -1, -1, sizeof(::GameMessage::GameSnapshotMessage)},
  { 19, -1, -1, sizeof(::GameMessage::PlayerSync)},
  { 29, -1, -1, sizeof(::GameMessage::PlayerSnapshotSync)},
  { 39, -1, -1, sizeof(::GameMessage::ObjectSnapshotSync)},
  { 48, -1, -1, sizeof(::GameMessage::HeartBeat)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GameMessage::_GameSyncMessage_default_instance_._instance,
  &::GameMessage::_GameSnapshotMessage_default_instance_._instance,
  &::GameMessage::_PlayerSync_default_instance_._instance,
  &::GameMessage::_PlayerSnapshotSync_default_instance_._instance,
  &::GameMessage::_ObjectSnapshotSync_default_instance_._instance,
  &::GameMessage::_HeartBeat_default_instance_._instance,
};

const char descriptor_table_protodef_GameMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021GameMessage.proto\022\013GameMessage\032\017UnityM"
  "ath.proto\"Z\n\017GameSyncMessage\022\017\n\007frameId\030"
  "\001 \001(\004\022\014\n\004time\030\002 \001(\004\022(\n\007players\030\003 \003(\0132\027.G"
  "ameMessage.PlayerSync\"\243\001\n\023GameSnapshotMe"
  "ssage\022\017\n\007frameId\030\001 \001(\004\022\023\n\013lastFrameId\030\002 "
  "\001(\004\0222\n\tplayerSSs\030\003 \003(\0132\037.GameMessage.Pla"
  "yerSnapshotSync\0222\n\tobjectSSs\030\004 \003(\0132\037.Gam"
  "eMessage.ObjectSnapshotSync\"a\n\nPlayerSyn"
  "c\022\017\n\007frameId\030\001 \001(\004\022\014\n\004time\030\002 \001(\004\022\014\n\004name"
  "\030\003 \001(\t\022&\n\tinputMove\030\004 \001(\0132\023.UnityMath.Ve"
  "ctor3D\"|\n\022PlayerSnapshotSync\022\014\n\004name\030\001 \001"
  "(\t\022\017\n\007frameId\030\002 \001(\004\022 \n\003pos\030\003 \001(\0132\023.Unity"
  "Math.Vector3D\022%\n\010velocity\030\004 \001(\0132\023.UnityM"
  "ath.Vector3D\"o\n\022ObjectSnapshotSync\022\020\n\010ob"
  "jectId\030\001 \001(\004\022 \n\003pos\030\002 \001(\0132\023.UnityMath.Ve"
  "ctor3D\022%\n\010velocity\030\003 \001(\0132\023.UnityMath.Vec"
  "tor3D\"\'\n\tHeartBeat\022\014\n\004name\030\001 \001(\t\022\014\n\004time"
  "\030\002 \001(\004b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_GameMessage_2eproto_deps[1] = {
  &::descriptor_table_UnityMath_2eproto,
};
static ::_pbi::once_flag descriptor_table_GameMessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GameMessage_2eproto = {
    false, false, 694, descriptor_table_protodef_GameMessage_2eproto,
    "GameMessage.proto",
    &descriptor_table_GameMessage_2eproto_once, descriptor_table_GameMessage_2eproto_deps, 1, 6,
    schemas, file_default_instances, TableStruct_GameMessage_2eproto::offsets,
    file_level_metadata_GameMessage_2eproto, file_level_enum_descriptors_GameMessage_2eproto,
    file_level_service_descriptors_GameMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GameMessage_2eproto_getter() {
  return &descriptor_table_GameMessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GameMessage_2eproto(&descriptor_table_GameMessage_2eproto);
namespace GameMessage {

// ===================================================================

class GameSyncMessage::_Internal {
 public:
};

GameSyncMessage::GameSyncMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.GameSyncMessage)
}
GameSyncMessage::GameSyncMessage(const GameSyncMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameSyncMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){from._impl_.players_}
    , decltype(_impl_.frameid_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.frameid_, &from._impl_.frameid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.time_) -
    reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.time_));
  // @@protoc_insertion_point(copy_constructor:GameMessage.GameSyncMessage)
}

inline void GameSyncMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){arena}
    , decltype(_impl_.frameid_){uint64_t{0u}}
    , decltype(_impl_.time_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameSyncMessage::~GameSyncMessage() {
  // @@protoc_insertion_point(destructor:GameMessage.GameSyncMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GameSyncMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.players_.~RepeatedPtrField();
}

void GameSyncMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameSyncMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.GameSyncMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.players_.Clear();
  ::memset(&_impl_.frameid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.time_) -
      reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.time_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameSyncMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 frameId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .GameMessage.PlayerSync players = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_players(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameSyncMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.GameSyncMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_frameid(), target);
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_time(), target);
  }

  // repeated .GameMessage.PlayerSync players = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_players_size()); i < n; i++) {
    const auto& repfield = this->_internal_players(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.GameSyncMessage)
  return target;
}

size_t GameSyncMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.GameSyncMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GameMessage.PlayerSync players = 3;
  total_size += 1UL * this->_internal_players_size();
  for (const auto& msg : this->_impl_.players_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frameid());
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameSyncMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameSyncMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameSyncMessage::GetClassData() const { return &_class_data_; }


void GameSyncMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameSyncMessage*>(&to_msg);
  auto& from = static_cast<const GameSyncMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.GameSyncMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.players_.MergeFrom(from._impl_.players_);
  if (from._internal_frameid() != 0) {
    _this->_internal_set_frameid(from._internal_frameid());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameSyncMessage::CopyFrom(const GameSyncMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.GameSyncMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameSyncMessage::IsInitialized() const {
  return true;
}

void GameSyncMessage::InternalSwap(GameSyncMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.players_.InternalSwap(&other->_impl_.players_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameSyncMessage, _impl_.time_)
      + sizeof(GameSyncMessage::_impl_.time_)
      - PROTOBUF_FIELD_OFFSET(GameSyncMessage, _impl_.frameid_)>(
          reinterpret_cast<char*>(&_impl_.frameid_),
          reinterpret_cast<char*>(&other->_impl_.frameid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameSyncMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[0]);
}

// ===================================================================

class GameSnapshotMessage::_Internal {
 public:
};

GameSnapshotMessage::GameSnapshotMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.GameSnapshotMessage)
}
GameSnapshotMessage::GameSnapshotMessage(const GameSnapshotMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameSnapshotMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playersss_){from._impl_.playersss_}
    , decltype(_impl_.objectsss_){from._impl_.objectsss_}
    , decltype(_impl_.frameid_){}
    , decltype(_impl_.lastframeid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.frameid_, &from._impl_.frameid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lastframeid_) -
    reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.lastframeid_));
  // @@protoc_insertion_point(copy_constructor:GameMessage.GameSnapshotMessage)
}

inline void GameSnapshotMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playersss_){arena}
    , decltype(_impl_.objectsss_){arena}
    , decltype(_impl_.frameid_){uint64_t{0u}}
    , decltype(_impl_.lastframeid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameSnapshotMessage::~GameSnapshotMessage() {
  // @@protoc_insertion_point(destructor:GameMessage.GameSnapshotMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GameSnapshotMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.playersss_.~RepeatedPtrField();
  _impl_.objectsss_.~RepeatedPtrField();
}

void GameSnapshotMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameSnapshotMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.GameSnapshotMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playersss_.Clear();
  _impl_.objectsss_.Clear();
  ::memset(&_impl_.frameid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lastframeid_) -
      reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.lastframeid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameSnapshotMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 frameId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 lastFrameId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.lastframeid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .GameMessage.PlayerSnapshotSync playerSSs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_playersss(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .GameMessage.ObjectSnapshotSync objectSSs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_objectsss(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameSnapshotMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.GameSnapshotMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_frameid(), target);
  }

  // uint64 lastFrameId = 2;
  if (this->_internal_lastframeid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_lastframeid(), target);
  }

  // repeated .GameMessage.PlayerSnapshotSync playerSSs = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_playersss_size()); i < n; i++) {
    const auto& repfield = this->_internal_playersss(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .GameMessage.ObjectSnapshotSync objectSSs = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_objectsss_size()); i < n; i++) {
    const auto& repfield = this->_internal_objectsss(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.GameSnapshotMessage)
  return target;
}

size_t GameSnapshotMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.GameSnapshotMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GameMessage.PlayerSnapshotSync playerSSs = 3;
  total_size += 1UL * this->_internal_playersss_size();
  for (const auto& msg : this->_impl_.playersss_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .GameMessage.ObjectSnapshotSync objectSSs = 4;
  total_size += 1UL * this->_internal_objectsss_size();
  for (const auto& msg : this->_impl_.objectsss_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frameid());
  }

  // uint64 lastFrameId = 2;
  if (this->_internal_lastframeid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_lastframeid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameSnapshotMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameSnapshotMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameSnapshotMessage::GetClassData() const { return &_class_data_; }


void GameSnapshotMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameSnapshotMessage*>(&to_msg);
  auto& from = static_cast<const GameSnapshotMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.GameSnapshotMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.playersss_.MergeFrom(from._impl_.playersss_);
  _this->_impl_.objectsss_.MergeFrom(from._impl_.objectsss_);
  if (from._internal_frameid() != 0) {
    _this->_internal_set_frameid(from._internal_frameid());
  }
  if (from._internal_lastframeid() != 0) {
    _this->_internal_set_lastframeid(from._internal_lastframeid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameSnapshotMessage::CopyFrom(const GameSnapshotMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.GameSnapshotMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameSnapshotMessage::IsInitialized() const {
  return true;
}

void GameSnapshotMessage::InternalSwap(GameSnapshotMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.playersss_.InternalSwap(&other->_impl_.playersss_);
  _impl_.objectsss_.InternalSwap(&other->_impl_.objectsss_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameSnapshotMessage, _impl_.lastframeid_)
      + sizeof(GameSnapshotMessage::_impl_.lastframeid_)
      - PROTOBUF_FIELD_OFFSET(GameSnapshotMessage, _impl_.frameid_)>(
          reinterpret_cast<char*>(&_impl_.frameid_),
          reinterpret_cast<char*>(&other->_impl_.frameid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameSnapshotMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[1]);
}

// ===================================================================

class PlayerSync::_Internal {
 public:
  static const ::UnityMath::Vector3D& inputmove(const PlayerSync* msg);
};

const ::UnityMath::Vector3D&
PlayerSync::_Internal::inputmove(const PlayerSync* msg) {
  return *msg->_impl_.inputmove_;
}
void PlayerSync::clear_inputmove() {
  if (GetArenaForAllocation() == nullptr && _impl_.inputmove_ != nullptr) {
    delete _impl_.inputmove_;
  }
  _impl_.inputmove_ = nullptr;
}
PlayerSync::PlayerSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.PlayerSync)
}
PlayerSync::PlayerSync(const PlayerSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.inputmove_){nullptr}
    , decltype(_impl_.frameid_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_inputmove()) {
    _this->_impl_.inputmove_ = new ::UnityMath::Vector3D(*from._impl_.inputmove_);
  }
  ::memcpy(&_impl_.frameid_, &from._impl_.frameid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.time_) -
    reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.time_));
  // @@protoc_insertion_point(copy_constructor:GameMessage.PlayerSync)
}

inline void PlayerSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.inputmove_){nullptr}
    , decltype(_impl_.frameid_){uint64_t{0u}}
    , decltype(_impl_.time_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerSync::~PlayerSync() {
  // @@protoc_insertion_point(destructor:GameMessage.PlayerSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.inputmove_;
}

void PlayerSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerSync::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.PlayerSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.inputmove_ != nullptr) {
    delete _impl_.inputmove_;
  }
  _impl_.inputmove_ = nullptr;
  ::memset(&_impl_.frameid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.time_) -
      reinterpret_cast<char*>(&_impl_.frameid_)) + sizeof(_impl_.time_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 frameId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GameMessage.PlayerSync.name"));
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D inputMove = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_inputmove(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.PlayerSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_frameid(), target);
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_time(), target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GameMessage.PlayerSync.name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_name(), target);
  }

  // .UnityMath.Vector3D inputMove = 4;
  if (this->_internal_has_inputmove()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::inputmove(this),
        _Internal::inputmove(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.PlayerSync)
  return target;
}

size_t PlayerSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.PlayerSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .UnityMath.Vector3D inputMove = 4;
  if (this->_internal_has_inputmove()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.inputmove_);
  }

  // uint64 frameId = 1;
  if (this->_internal_frameid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frameid());
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerSync::GetClassData() const { return &_class_data_; }


void PlayerSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerSync*>(&to_msg);
  auto& from = static_cast<const PlayerSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.PlayerSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_has_inputmove()) {
    _this->_internal_mutable_inputmove()->::UnityMath::Vector3D::MergeFrom(
        from._internal_inputmove());
  }
  if (from._internal_frameid() != 0) {
    _this->_internal_set_frameid(from._internal_frameid());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerSync::CopyFrom(const PlayerSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.PlayerSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerSync::IsInitialized() const {
  return true;
}

void PlayerSync::InternalSwap(PlayerSync* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerSync, _impl_.time_)
      + sizeof(PlayerSync::_impl_.time_)
      - PROTOBUF_FIELD_OFFSET(PlayerSync, _impl_.inputmove_)>(
          reinterpret_cast<char*>(&_impl_.inputmove_),
          reinterpret_cast<char*>(&other->_impl_.inputmove_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[2]);
}

// ===================================================================

class PlayerSnapshotSync::_Internal {
 public:
  static const ::UnityMath::Vector3D& pos(const PlayerSnapshotSync* msg);
  static const ::UnityMath::Vector3D& velocity(const PlayerSnapshotSync* msg);
};

const ::UnityMath::Vector3D&
PlayerSnapshotSync::_Internal::pos(const PlayerSnapshotSync* msg) {
  return *msg->_impl_.pos_;
}
const ::UnityMath::Vector3D&
PlayerSnapshotSync::_Internal::velocity(const PlayerSnapshotSync* msg) {
  return *msg->_impl_.velocity_;
}
void PlayerSnapshotSync::clear_pos() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
}
void PlayerSnapshotSync::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
}
PlayerSnapshotSync::PlayerSnapshotSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.PlayerSnapshotSync)
}
PlayerSnapshotSync::PlayerSnapshotSync(const PlayerSnapshotSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerSnapshotSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.frameid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_pos()) {
    _this->_impl_.pos_ = new ::UnityMath::Vector3D(*from._impl_.pos_);
  }
  if (from._internal_has_velocity()) {
    _this->_impl_.velocity_ = new ::UnityMath::Vector3D(*from._impl_.velocity_);
  }
  _this->_impl_.frameid_ = from._impl_.frameid_;
  // @@protoc_insertion_point(copy_constructor:GameMessage.PlayerSnapshotSync)
}

inline void PlayerSnapshotSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.frameid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerSnapshotSync::~PlayerSnapshotSync() {
  // @@protoc_insertion_point(destructor:GameMessage.PlayerSnapshotSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerSnapshotSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.pos_;
  if (this != internal_default_instance()) delete _impl_.velocity_;
}

void PlayerSnapshotSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerSnapshotSync::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.PlayerSnapshotSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
  _impl_.frameid_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerSnapshotSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GameMessage.PlayerSnapshotSync.name"));
        } else
          goto handle_unusual;
        continue;
      // uint64 frameId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.frameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D pos = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_pos(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D velocity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerSnapshotSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.PlayerSnapshotSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GameMessage.PlayerSnapshotSync.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // uint64 frameId = 2;
  if (this->_internal_frameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_frameid(), target);
  }

  // .UnityMath.Vector3D pos = 3;
  if (this->_internal_has_pos()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::pos(this),
        _Internal::pos(this).GetCachedSize(), target, stream);
  }

  // .UnityMath.Vector3D velocity = 4;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.PlayerSnapshotSync)
  return target;
}

size_t PlayerSnapshotSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.PlayerSnapshotSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .UnityMath.Vector3D pos = 3;
  if (this->_internal_has_pos()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.pos_);
  }

  // .UnityMath.Vector3D velocity = 4;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.velocity_);
  }

  // uint64 frameId = 2;
  if (this->_internal_frameid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frameid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerSnapshotSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerSnapshotSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerSnapshotSync::GetClassData() const { return &_class_data_; }


void PlayerSnapshotSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerSnapshotSync*>(&to_msg);
  auto& from = static_cast<const PlayerSnapshotSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.PlayerSnapshotSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_has_pos()) {
    _this->_internal_mutable_pos()->::UnityMath::Vector3D::MergeFrom(
        from._internal_pos());
  }
  if (from._internal_has_velocity()) {
    _this->_internal_mutable_velocity()->::UnityMath::Vector3D::MergeFrom(
        from._internal_velocity());
  }
  if (from._internal_frameid() != 0) {
    _this->_internal_set_frameid(from._internal_frameid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerSnapshotSync::CopyFrom(const PlayerSnapshotSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.PlayerSnapshotSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerSnapshotSync::IsInitialized() const {
  return true;
}

void PlayerSnapshotSync::InternalSwap(PlayerSnapshotSync* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerSnapshotSync, _impl_.frameid_)
      + sizeof(PlayerSnapshotSync::_impl_.frameid_)
      - PROTOBUF_FIELD_OFFSET(PlayerSnapshotSync, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerSnapshotSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[3]);
}

// ===================================================================

class ObjectSnapshotSync::_Internal {
 public:
  static const ::UnityMath::Vector3D& pos(const ObjectSnapshotSync* msg);
  static const ::UnityMath::Vector3D& velocity(const ObjectSnapshotSync* msg);
};

const ::UnityMath::Vector3D&
ObjectSnapshotSync::_Internal::pos(const ObjectSnapshotSync* msg) {
  return *msg->_impl_.pos_;
}
const ::UnityMath::Vector3D&
ObjectSnapshotSync::_Internal::velocity(const ObjectSnapshotSync* msg) {
  return *msg->_impl_.velocity_;
}
void ObjectSnapshotSync::clear_pos() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
}
void ObjectSnapshotSync::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
}
ObjectSnapshotSync::ObjectSnapshotSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.ObjectSnapshotSync)
}
ObjectSnapshotSync::ObjectSnapshotSync(const ObjectSnapshotSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ObjectSnapshotSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.objectid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_pos()) {
    _this->_impl_.pos_ = new ::UnityMath::Vector3D(*from._impl_.pos_);
  }
  if (from._internal_has_velocity()) {
    _this->_impl_.velocity_ = new ::UnityMath::Vector3D(*from._impl_.velocity_);
  }
  _this->_impl_.objectid_ = from._impl_.objectid_;
  // @@protoc_insertion_point(copy_constructor:GameMessage.ObjectSnapshotSync)
}

inline void ObjectSnapshotSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.objectid_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ObjectSnapshotSync::~ObjectSnapshotSync() {
  // @@protoc_insertion_point(destructor:GameMessage.ObjectSnapshotSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ObjectSnapshotSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.pos_;
  if (this != internal_default_instance()) delete _impl_.velocity_;
}

void ObjectSnapshotSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ObjectSnapshotSync::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.ObjectSnapshotSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
  _impl_.objectid_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObjectSnapshotSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 objectId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D pos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_pos(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D velocity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ObjectSnapshotSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.ObjectSnapshotSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_objectid(), target);
  }

  // .UnityMath.Vector3D pos = 2;
  if (this->_internal_has_pos()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::pos(this),
        _Internal::pos(this).GetCachedSize(), target, stream);
  }

  // .UnityMath.Vector3D velocity = 3;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.ObjectSnapshotSync)
  return target;
}

size_t ObjectSnapshotSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.ObjectSnapshotSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .UnityMath.Vector3D pos = 2;
  if (this->_internal_has_pos()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.pos_);
  }

  // .UnityMath.Vector3D velocity = 3;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.velocity_);
  }

  // uint64 objectId = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_objectid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ObjectSnapshotSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ObjectSnapshotSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ObjectSnapshotSync::GetClassData() const { return &_class_data_; }


void ObjectSnapshotSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ObjectSnapshotSync*>(&to_msg);
  auto& from = static_cast<const ObjectSnapshotSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.ObjectSnapshotSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_pos()) {
    _this->_internal_mutable_pos()->::UnityMath::Vector3D::MergeFrom(
        from._internal_pos());
  }
  if (from._internal_has_velocity()) {
    _this->_internal_mutable_velocity()->::UnityMath::Vector3D::MergeFrom(
        from._internal_velocity());
  }
  if (from._internal_objectid() != 0) {
    _this->_internal_set_objectid(from._internal_objectid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ObjectSnapshotSync::CopyFrom(const ObjectSnapshotSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.ObjectSnapshotSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectSnapshotSync::IsInitialized() const {
  return true;
}

void ObjectSnapshotSync::InternalSwap(ObjectSnapshotSync* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObjectSnapshotSync, _impl_.objectid_)
      + sizeof(ObjectSnapshotSync::_impl_.objectid_)
      - PROTOBUF_FIELD_OFFSET(ObjectSnapshotSync, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObjectSnapshotSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[4]);
}

// ===================================================================

class HeartBeat::_Internal {
 public:
};

HeartBeat::HeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GameMessage.HeartBeat)
}
HeartBeat::HeartBeat(const HeartBeat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeartBeat* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.time_ = from._impl_.time_;
  // @@protoc_insertion_point(copy_constructor:GameMessage.HeartBeat)
}

inline void HeartBeat::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.time_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

HeartBeat::~HeartBeat() {
  // @@protoc_insertion_point(destructor:GameMessage.HeartBeat)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeartBeat::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void HeartBeat::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeartBeat::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMessage.HeartBeat)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.time_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeartBeat::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GameMessage.HeartBeat.name"));
        } else
          goto handle_unusual;
        continue;
      // uint64 time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeartBeat::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameMessage.HeartBeat)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GameMessage.HeartBeat.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameMessage.HeartBeat)
  return target;
}

size_t HeartBeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameMessage.HeartBeat)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // uint64 time = 2;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartBeat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeartBeat::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartBeat::GetClassData() const { return &_class_data_; }


void HeartBeat::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeartBeat*>(&to_msg);
  auto& from = static_cast<const HeartBeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMessage.HeartBeat)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeartBeat::CopyFrom(const HeartBeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMessage.HeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartBeat::IsInitialized() const {
  return true;
}

void HeartBeat::InternalSwap(HeartBeat* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.time_, other->_impl_.time_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HeartBeat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameMessage_2eproto_getter, &descriptor_table_GameMessage_2eproto_once,
      file_level_metadata_GameMessage_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GameMessage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GameMessage::GameSyncMessage*
Arena::CreateMaybeMessage< ::GameMessage::GameSyncMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::GameSyncMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::GameMessage::GameSnapshotMessage*
Arena::CreateMaybeMessage< ::GameMessage::GameSnapshotMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::GameSnapshotMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::GameMessage::PlayerSync*
Arena::CreateMaybeMessage< ::GameMessage::PlayerSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::PlayerSync >(arena);
}
template<> PROTOBUF_NOINLINE ::GameMessage::PlayerSnapshotSync*
Arena::CreateMaybeMessage< ::GameMessage::PlayerSnapshotSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::PlayerSnapshotSync >(arena);
}
template<> PROTOBUF_NOINLINE ::GameMessage::ObjectSnapshotSync*
Arena::CreateMaybeMessage< ::GameMessage::ObjectSnapshotSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::ObjectSnapshotSync >(arena);
}
template<> PROTOBUF_NOINLINE ::GameMessage::HeartBeat*
Arena::CreateMaybeMessage< ::GameMessage::HeartBeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GameMessage::HeartBeat >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
