// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobbyMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_LobbyMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_LobbyMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_LobbyMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_LobbyMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LobbyMessage_2eproto;
namespace LobbyMessage {
class LobbySyncRequest;
struct LobbySyncRequestDefaultTypeInternal;
extern LobbySyncRequestDefaultTypeInternal _LobbySyncRequest_default_instance_;
class LobbySyncResponse;
struct LobbySyncResponseDefaultTypeInternal;
extern LobbySyncResponseDefaultTypeInternal _LobbySyncResponse_default_instance_;
class PlayerJoinRoomRequest;
struct PlayerJoinRoomRequestDefaultTypeInternal;
extern PlayerJoinRoomRequestDefaultTypeInternal _PlayerJoinRoomRequest_default_instance_;
class PlayerJoinRoomResponse;
struct PlayerJoinRoomResponseDefaultTypeInternal;
extern PlayerJoinRoomResponseDefaultTypeInternal _PlayerJoinRoomResponse_default_instance_;
class PlayerLoginRequest;
struct PlayerLoginRequestDefaultTypeInternal;
extern PlayerLoginRequestDefaultTypeInternal _PlayerLoginRequest_default_instance_;
class PlayerLoginResponse;
struct PlayerLoginResponseDefaultTypeInternal;
extern PlayerLoginResponseDefaultTypeInternal _PlayerLoginResponse_default_instance_;
class PlayerPlayRoomRequest;
struct PlayerPlayRoomRequestDefaultTypeInternal;
extern PlayerPlayRoomRequestDefaultTypeInternal _PlayerPlayRoomRequest_default_instance_;
class PlayerPlayRoomResponse;
struct PlayerPlayRoomResponseDefaultTypeInternal;
extern PlayerPlayRoomResponseDefaultTypeInternal _PlayerPlayRoomResponse_default_instance_;
}  // namespace LobbyMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::LobbyMessage::LobbySyncRequest* Arena::CreateMaybeMessage<::LobbyMessage::LobbySyncRequest>(Arena*);
template<> ::LobbyMessage::LobbySyncResponse* Arena::CreateMaybeMessage<::LobbyMessage::LobbySyncResponse>(Arena*);
template<> ::LobbyMessage::PlayerJoinRoomRequest* Arena::CreateMaybeMessage<::LobbyMessage::PlayerJoinRoomRequest>(Arena*);
template<> ::LobbyMessage::PlayerJoinRoomResponse* Arena::CreateMaybeMessage<::LobbyMessage::PlayerJoinRoomResponse>(Arena*);
template<> ::LobbyMessage::PlayerLoginRequest* Arena::CreateMaybeMessage<::LobbyMessage::PlayerLoginRequest>(Arena*);
template<> ::LobbyMessage::PlayerLoginResponse* Arena::CreateMaybeMessage<::LobbyMessage::PlayerLoginResponse>(Arena*);
template<> ::LobbyMessage::PlayerPlayRoomRequest* Arena::CreateMaybeMessage<::LobbyMessage::PlayerPlayRoomRequest>(Arena*);
template<> ::LobbyMessage::PlayerPlayRoomResponse* Arena::CreateMaybeMessage<::LobbyMessage::PlayerPlayRoomResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace LobbyMessage {

// ===================================================================

class LobbySyncRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.LobbySyncRequest) */ {
 public:
  inline LobbySyncRequest() : LobbySyncRequest(nullptr) {}
  ~LobbySyncRequest() override;
  explicit PROTOBUF_CONSTEXPR LobbySyncRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LobbySyncRequest(const LobbySyncRequest& from);
  LobbySyncRequest(LobbySyncRequest&& from) noexcept
    : LobbySyncRequest() {
    *this = ::std::move(from);
  }

  inline LobbySyncRequest& operator=(const LobbySyncRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LobbySyncRequest& operator=(LobbySyncRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LobbySyncRequest& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kPlayerLogin = 2,
    kPlayerJoin = 3,
    kPlayerPlayRoom = 4,
    CONTENT_NOT_SET = 0,
  };

  static inline const LobbySyncRequest* internal_default_instance() {
    return reinterpret_cast<const LobbySyncRequest*>(
               &_LobbySyncRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LobbySyncRequest& a, LobbySyncRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LobbySyncRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LobbySyncRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LobbySyncRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LobbySyncRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LobbySyncRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LobbySyncRequest& from) {
    LobbySyncRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LobbySyncRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.LobbySyncRequest";
  }
  protected:
  explicit LobbySyncRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPlayerLoginFieldNumber = 2,
    kPlayerJoinFieldNumber = 3,
    kPlayerPlayRoomFieldNumber = 4,
  };
  // uint64 playerId = 1;
  void clear_playerid();
  uint64_t playerid() const;
  void set_playerid(uint64_t value);
  private:
  uint64_t _internal_playerid() const;
  void _internal_set_playerid(uint64_t value);
  public:

  // .LobbyMessage.PlayerLoginRequest playerLogin = 2;
  bool has_playerlogin() const;
  private:
  bool _internal_has_playerlogin() const;
  public:
  void clear_playerlogin();
  const ::LobbyMessage::PlayerLoginRequest& playerlogin() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerLoginRequest* release_playerlogin();
  ::LobbyMessage::PlayerLoginRequest* mutable_playerlogin();
  void set_allocated_playerlogin(::LobbyMessage::PlayerLoginRequest* playerlogin);
  private:
  const ::LobbyMessage::PlayerLoginRequest& _internal_playerlogin() const;
  ::LobbyMessage::PlayerLoginRequest* _internal_mutable_playerlogin();
  public:
  void unsafe_arena_set_allocated_playerlogin(
      ::LobbyMessage::PlayerLoginRequest* playerlogin);
  ::LobbyMessage::PlayerLoginRequest* unsafe_arena_release_playerlogin();

  // .LobbyMessage.PlayerJoinRoomRequest playerJoin = 3;
  bool has_playerjoin() const;
  private:
  bool _internal_has_playerjoin() const;
  public:
  void clear_playerjoin();
  const ::LobbyMessage::PlayerJoinRoomRequest& playerjoin() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerJoinRoomRequest* release_playerjoin();
  ::LobbyMessage::PlayerJoinRoomRequest* mutable_playerjoin();
  void set_allocated_playerjoin(::LobbyMessage::PlayerJoinRoomRequest* playerjoin);
  private:
  const ::LobbyMessage::PlayerJoinRoomRequest& _internal_playerjoin() const;
  ::LobbyMessage::PlayerJoinRoomRequest* _internal_mutable_playerjoin();
  public:
  void unsafe_arena_set_allocated_playerjoin(
      ::LobbyMessage::PlayerJoinRoomRequest* playerjoin);
  ::LobbyMessage::PlayerJoinRoomRequest* unsafe_arena_release_playerjoin();

  // .LobbyMessage.PlayerPlayRoomRequest playerPlayRoom = 4;
  bool has_playerplayroom() const;
  private:
  bool _internal_has_playerplayroom() const;
  public:
  void clear_playerplayroom();
  const ::LobbyMessage::PlayerPlayRoomRequest& playerplayroom() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerPlayRoomRequest* release_playerplayroom();
  ::LobbyMessage::PlayerPlayRoomRequest* mutable_playerplayroom();
  void set_allocated_playerplayroom(::LobbyMessage::PlayerPlayRoomRequest* playerplayroom);
  private:
  const ::LobbyMessage::PlayerPlayRoomRequest& _internal_playerplayroom() const;
  ::LobbyMessage::PlayerPlayRoomRequest* _internal_mutable_playerplayroom();
  public:
  void unsafe_arena_set_allocated_playerplayroom(
      ::LobbyMessage::PlayerPlayRoomRequest* playerplayroom);
  ::LobbyMessage::PlayerPlayRoomRequest* unsafe_arena_release_playerplayroom();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:LobbyMessage.LobbySyncRequest)
 private:
  class _Internal;
  void set_has_playerlogin();
  void set_has_playerjoin();
  void set_has_playerplayroom();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t playerid_;
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::LobbyMessage::PlayerLoginRequest* playerlogin_;
      ::LobbyMessage::PlayerJoinRoomRequest* playerjoin_;
      ::LobbyMessage::PlayerPlayRoomRequest* playerplayroom_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerLoginRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerLoginRequest) */ {
 public:
  inline PlayerLoginRequest() : PlayerLoginRequest(nullptr) {}
  ~PlayerLoginRequest() override;
  explicit PROTOBUF_CONSTEXPR PlayerLoginRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerLoginRequest(const PlayerLoginRequest& from);
  PlayerLoginRequest(PlayerLoginRequest&& from) noexcept
    : PlayerLoginRequest() {
    *this = ::std::move(from);
  }

  inline PlayerLoginRequest& operator=(const PlayerLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerLoginRequest& operator=(PlayerLoginRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerLoginRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerLoginRequest* internal_default_instance() {
    return reinterpret_cast<const PlayerLoginRequest*>(
               &_PlayerLoginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerLoginRequest& a, PlayerLoginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerLoginRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerLoginRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerLoginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerLoginRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerLoginRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerLoginRequest& from) {
    PlayerLoginRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerLoginRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerLoginRequest";
  }
  protected:
  explicit PlayerLoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerLoginRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerJoinRoomRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerJoinRoomRequest) */ {
 public:
  inline PlayerJoinRoomRequest() : PlayerJoinRoomRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR PlayerJoinRoomRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerJoinRoomRequest(const PlayerJoinRoomRequest& from);
  PlayerJoinRoomRequest(PlayerJoinRoomRequest&& from) noexcept
    : PlayerJoinRoomRequest() {
    *this = ::std::move(from);
  }

  inline PlayerJoinRoomRequest& operator=(const PlayerJoinRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerJoinRoomRequest& operator=(PlayerJoinRoomRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerJoinRoomRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerJoinRoomRequest* internal_default_instance() {
    return reinterpret_cast<const PlayerJoinRoomRequest*>(
               &_PlayerJoinRoomRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerJoinRoomRequest& a, PlayerJoinRoomRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerJoinRoomRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerJoinRoomRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerJoinRoomRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerJoinRoomRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PlayerJoinRoomRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PlayerJoinRoomRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerJoinRoomRequest";
  }
  protected:
  explicit PlayerJoinRoomRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerJoinRoomRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerPlayRoomRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerPlayRoomRequest) */ {
 public:
  inline PlayerPlayRoomRequest() : PlayerPlayRoomRequest(nullptr) {}
  ~PlayerPlayRoomRequest() override;
  explicit PROTOBUF_CONSTEXPR PlayerPlayRoomRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerPlayRoomRequest(const PlayerPlayRoomRequest& from);
  PlayerPlayRoomRequest(PlayerPlayRoomRequest&& from) noexcept
    : PlayerPlayRoomRequest() {
    *this = ::std::move(from);
  }

  inline PlayerPlayRoomRequest& operator=(const PlayerPlayRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerPlayRoomRequest& operator=(PlayerPlayRoomRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerPlayRoomRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerPlayRoomRequest* internal_default_instance() {
    return reinterpret_cast<const PlayerPlayRoomRequest*>(
               &_PlayerPlayRoomRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlayerPlayRoomRequest& a, PlayerPlayRoomRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerPlayRoomRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerPlayRoomRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerPlayRoomRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerPlayRoomRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerPlayRoomRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerPlayRoomRequest& from) {
    PlayerPlayRoomRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerPlayRoomRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerPlayRoomRequest";
  }
  protected:
  explicit PlayerPlayRoomRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
  };
  // uint64 roomId = 1;
  void clear_roomid();
  uint64_t roomid() const;
  void set_roomid(uint64_t value);
  private:
  uint64_t _internal_roomid() const;
  void _internal_set_roomid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerPlayRoomRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t roomid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class LobbySyncResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.LobbySyncResponse) */ {
 public:
  inline LobbySyncResponse() : LobbySyncResponse(nullptr) {}
  ~LobbySyncResponse() override;
  explicit PROTOBUF_CONSTEXPR LobbySyncResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LobbySyncResponse(const LobbySyncResponse& from);
  LobbySyncResponse(LobbySyncResponse&& from) noexcept
    : LobbySyncResponse() {
    *this = ::std::move(from);
  }

  inline LobbySyncResponse& operator=(const LobbySyncResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LobbySyncResponse& operator=(LobbySyncResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LobbySyncResponse& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kPlayerLogin = 1,
    kPlayerJoin = 2,
    kPlayerPlayRoom = 3,
    CONTENT_NOT_SET = 0,
  };

  static inline const LobbySyncResponse* internal_default_instance() {
    return reinterpret_cast<const LobbySyncResponse*>(
               &_LobbySyncResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LobbySyncResponse& a, LobbySyncResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LobbySyncResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LobbySyncResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LobbySyncResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LobbySyncResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LobbySyncResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LobbySyncResponse& from) {
    LobbySyncResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LobbySyncResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.LobbySyncResponse";
  }
  protected:
  explicit LobbySyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerLoginFieldNumber = 1,
    kPlayerJoinFieldNumber = 2,
    kPlayerPlayRoomFieldNumber = 3,
  };
  // .LobbyMessage.PlayerLoginResponse playerLogin = 1;
  bool has_playerlogin() const;
  private:
  bool _internal_has_playerlogin() const;
  public:
  void clear_playerlogin();
  const ::LobbyMessage::PlayerLoginResponse& playerlogin() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerLoginResponse* release_playerlogin();
  ::LobbyMessage::PlayerLoginResponse* mutable_playerlogin();
  void set_allocated_playerlogin(::LobbyMessage::PlayerLoginResponse* playerlogin);
  private:
  const ::LobbyMessage::PlayerLoginResponse& _internal_playerlogin() const;
  ::LobbyMessage::PlayerLoginResponse* _internal_mutable_playerlogin();
  public:
  void unsafe_arena_set_allocated_playerlogin(
      ::LobbyMessage::PlayerLoginResponse* playerlogin);
  ::LobbyMessage::PlayerLoginResponse* unsafe_arena_release_playerlogin();

  // .LobbyMessage.PlayerJoinRoomResponse playerJoin = 2;
  bool has_playerjoin() const;
  private:
  bool _internal_has_playerjoin() const;
  public:
  void clear_playerjoin();
  const ::LobbyMessage::PlayerJoinRoomResponse& playerjoin() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerJoinRoomResponse* release_playerjoin();
  ::LobbyMessage::PlayerJoinRoomResponse* mutable_playerjoin();
  void set_allocated_playerjoin(::LobbyMessage::PlayerJoinRoomResponse* playerjoin);
  private:
  const ::LobbyMessage::PlayerJoinRoomResponse& _internal_playerjoin() const;
  ::LobbyMessage::PlayerJoinRoomResponse* _internal_mutable_playerjoin();
  public:
  void unsafe_arena_set_allocated_playerjoin(
      ::LobbyMessage::PlayerJoinRoomResponse* playerjoin);
  ::LobbyMessage::PlayerJoinRoomResponse* unsafe_arena_release_playerjoin();

  // .LobbyMessage.PlayerPlayRoomResponse playerPlayRoom = 3;
  bool has_playerplayroom() const;
  private:
  bool _internal_has_playerplayroom() const;
  public:
  void clear_playerplayroom();
  const ::LobbyMessage::PlayerPlayRoomResponse& playerplayroom() const;
  PROTOBUF_NODISCARD ::LobbyMessage::PlayerPlayRoomResponse* release_playerplayroom();
  ::LobbyMessage::PlayerPlayRoomResponse* mutable_playerplayroom();
  void set_allocated_playerplayroom(::LobbyMessage::PlayerPlayRoomResponse* playerplayroom);
  private:
  const ::LobbyMessage::PlayerPlayRoomResponse& _internal_playerplayroom() const;
  ::LobbyMessage::PlayerPlayRoomResponse* _internal_mutable_playerplayroom();
  public:
  void unsafe_arena_set_allocated_playerplayroom(
      ::LobbyMessage::PlayerPlayRoomResponse* playerplayroom);
  ::LobbyMessage::PlayerPlayRoomResponse* unsafe_arena_release_playerplayroom();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:LobbyMessage.LobbySyncResponse)
 private:
  class _Internal;
  void set_has_playerlogin();
  void set_has_playerjoin();
  void set_has_playerplayroom();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::LobbyMessage::PlayerLoginResponse* playerlogin_;
      ::LobbyMessage::PlayerJoinRoomResponse* playerjoin_;
      ::LobbyMessage::PlayerPlayRoomResponse* playerplayroom_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerLoginResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerLoginResponse) */ {
 public:
  inline PlayerLoginResponse() : PlayerLoginResponse(nullptr) {}
  ~PlayerLoginResponse() override;
  explicit PROTOBUF_CONSTEXPR PlayerLoginResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerLoginResponse(const PlayerLoginResponse& from);
  PlayerLoginResponse(PlayerLoginResponse&& from) noexcept
    : PlayerLoginResponse() {
    *this = ::std::move(from);
  }

  inline PlayerLoginResponse& operator=(const PlayerLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerLoginResponse& operator=(PlayerLoginResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerLoginResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerLoginResponse* internal_default_instance() {
    return reinterpret_cast<const PlayerLoginResponse*>(
               &_PlayerLoginResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PlayerLoginResponse& a, PlayerLoginResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerLoginResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerLoginResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerLoginResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerLoginResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerLoginResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerLoginResponse& from) {
    PlayerLoginResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerLoginResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerLoginResponse";
  }
  protected:
  explicit PlayerLoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
  };
  // uint64 playerId = 1;
  void clear_playerid();
  uint64_t playerid() const;
  void set_playerid(uint64_t value);
  private:
  uint64_t _internal_playerid() const;
  void _internal_set_playerid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerLoginResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t playerid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerJoinRoomResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerJoinRoomResponse) */ {
 public:
  inline PlayerJoinRoomResponse() : PlayerJoinRoomResponse(nullptr) {}
  ~PlayerJoinRoomResponse() override;
  explicit PROTOBUF_CONSTEXPR PlayerJoinRoomResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerJoinRoomResponse(const PlayerJoinRoomResponse& from);
  PlayerJoinRoomResponse(PlayerJoinRoomResponse&& from) noexcept
    : PlayerJoinRoomResponse() {
    *this = ::std::move(from);
  }

  inline PlayerJoinRoomResponse& operator=(const PlayerJoinRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerJoinRoomResponse& operator=(PlayerJoinRoomResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerJoinRoomResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerJoinRoomResponse* internal_default_instance() {
    return reinterpret_cast<const PlayerJoinRoomResponse*>(
               &_PlayerJoinRoomResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(PlayerJoinRoomResponse& a, PlayerJoinRoomResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerJoinRoomResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerJoinRoomResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerJoinRoomResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerJoinRoomResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerJoinRoomResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerJoinRoomResponse& from) {
    PlayerJoinRoomResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerJoinRoomResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerJoinRoomResponse";
  }
  protected:
  explicit PlayerJoinRoomResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
  };
  // uint64 roomId = 1;
  void clear_roomid();
  uint64_t roomid() const;
  void set_roomid(uint64_t value);
  private:
  uint64_t _internal_roomid() const;
  void _internal_set_roomid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerJoinRoomResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t roomid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerPlayRoomResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LobbyMessage.PlayerPlayRoomResponse) */ {
 public:
  inline PlayerPlayRoomResponse() : PlayerPlayRoomResponse(nullptr) {}
  ~PlayerPlayRoomResponse() override;
  explicit PROTOBUF_CONSTEXPR PlayerPlayRoomResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerPlayRoomResponse(const PlayerPlayRoomResponse& from);
  PlayerPlayRoomResponse(PlayerPlayRoomResponse&& from) noexcept
    : PlayerPlayRoomResponse() {
    *this = ::std::move(from);
  }

  inline PlayerPlayRoomResponse& operator=(const PlayerPlayRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerPlayRoomResponse& operator=(PlayerPlayRoomResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerPlayRoomResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerPlayRoomResponse* internal_default_instance() {
    return reinterpret_cast<const PlayerPlayRoomResponse*>(
               &_PlayerPlayRoomResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(PlayerPlayRoomResponse& a, PlayerPlayRoomResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerPlayRoomResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerPlayRoomResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerPlayRoomResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerPlayRoomResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerPlayRoomResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerPlayRoomResponse& from) {
    PlayerPlayRoomResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerPlayRoomResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LobbyMessage.PlayerPlayRoomResponse";
  }
  protected:
  explicit PlayerPlayRoomResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
  };
  // uint64 roomId = 1;
  void clear_roomid();
  uint64_t roomid() const;
  void set_roomid(uint64_t value);
  private:
  uint64_t _internal_roomid() const;
  void _internal_set_roomid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:LobbyMessage.PlayerPlayRoomResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t roomid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LobbyMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LobbySyncRequest

// uint64 playerId = 1;
inline void LobbySyncRequest::clear_playerid() {
  _impl_.playerid_ = uint64_t{0u};
}
inline uint64_t LobbySyncRequest::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint64_t LobbySyncRequest::playerid() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncRequest.playerId)
  return _internal_playerid();
}
inline void LobbySyncRequest::_internal_set_playerid(uint64_t value) {
  
  _impl_.playerid_ = value;
}
inline void LobbySyncRequest::set_playerid(uint64_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:LobbyMessage.LobbySyncRequest.playerId)
}

// .LobbyMessage.PlayerLoginRequest playerLogin = 2;
inline bool LobbySyncRequest::_internal_has_playerlogin() const {
  return content_case() == kPlayerLogin;
}
inline bool LobbySyncRequest::has_playerlogin() const {
  return _internal_has_playerlogin();
}
inline void LobbySyncRequest::set_has_playerlogin() {
  _impl_._oneof_case_[0] = kPlayerLogin;
}
inline void LobbySyncRequest::clear_playerlogin() {
  if (_internal_has_playerlogin()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerlogin_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerLoginRequest* LobbySyncRequest::release_playerlogin() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncRequest.playerLogin)
  if (_internal_has_playerlogin()) {
    clear_has_content();
    ::LobbyMessage::PlayerLoginRequest* temp = _impl_.content_.playerlogin_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerlogin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerLoginRequest& LobbySyncRequest::_internal_playerlogin() const {
  return _internal_has_playerlogin()
      ? *_impl_.content_.playerlogin_
      : reinterpret_cast< ::LobbyMessage::PlayerLoginRequest&>(::LobbyMessage::_PlayerLoginRequest_default_instance_);
}
inline const ::LobbyMessage::PlayerLoginRequest& LobbySyncRequest::playerlogin() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncRequest.playerLogin)
  return _internal_playerlogin();
}
inline ::LobbyMessage::PlayerLoginRequest* LobbySyncRequest::unsafe_arena_release_playerlogin() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncRequest.playerLogin)
  if (_internal_has_playerlogin()) {
    clear_has_content();
    ::LobbyMessage::PlayerLoginRequest* temp = _impl_.content_.playerlogin_;
    _impl_.content_.playerlogin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncRequest::unsafe_arena_set_allocated_playerlogin(::LobbyMessage::PlayerLoginRequest* playerlogin) {
  clear_content();
  if (playerlogin) {
    set_has_playerlogin();
    _impl_.content_.playerlogin_ = playerlogin;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncRequest.playerLogin)
}
inline ::LobbyMessage::PlayerLoginRequest* LobbySyncRequest::_internal_mutable_playerlogin() {
  if (!_internal_has_playerlogin()) {
    clear_content();
    set_has_playerlogin();
    _impl_.content_.playerlogin_ = CreateMaybeMessage< ::LobbyMessage::PlayerLoginRequest >(GetArenaForAllocation());
  }
  return _impl_.content_.playerlogin_;
}
inline ::LobbyMessage::PlayerLoginRequest* LobbySyncRequest::mutable_playerlogin() {
  ::LobbyMessage::PlayerLoginRequest* _msg = _internal_mutable_playerlogin();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncRequest.playerLogin)
  return _msg;
}

// .LobbyMessage.PlayerJoinRoomRequest playerJoin = 3;
inline bool LobbySyncRequest::_internal_has_playerjoin() const {
  return content_case() == kPlayerJoin;
}
inline bool LobbySyncRequest::has_playerjoin() const {
  return _internal_has_playerjoin();
}
inline void LobbySyncRequest::set_has_playerjoin() {
  _impl_._oneof_case_[0] = kPlayerJoin;
}
inline void LobbySyncRequest::clear_playerjoin() {
  if (_internal_has_playerjoin()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerjoin_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerJoinRoomRequest* LobbySyncRequest::release_playerjoin() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncRequest.playerJoin)
  if (_internal_has_playerjoin()) {
    clear_has_content();
    ::LobbyMessage::PlayerJoinRoomRequest* temp = _impl_.content_.playerjoin_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerjoin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerJoinRoomRequest& LobbySyncRequest::_internal_playerjoin() const {
  return _internal_has_playerjoin()
      ? *_impl_.content_.playerjoin_
      : reinterpret_cast< ::LobbyMessage::PlayerJoinRoomRequest&>(::LobbyMessage::_PlayerJoinRoomRequest_default_instance_);
}
inline const ::LobbyMessage::PlayerJoinRoomRequest& LobbySyncRequest::playerjoin() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncRequest.playerJoin)
  return _internal_playerjoin();
}
inline ::LobbyMessage::PlayerJoinRoomRequest* LobbySyncRequest::unsafe_arena_release_playerjoin() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncRequest.playerJoin)
  if (_internal_has_playerjoin()) {
    clear_has_content();
    ::LobbyMessage::PlayerJoinRoomRequest* temp = _impl_.content_.playerjoin_;
    _impl_.content_.playerjoin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncRequest::unsafe_arena_set_allocated_playerjoin(::LobbyMessage::PlayerJoinRoomRequest* playerjoin) {
  clear_content();
  if (playerjoin) {
    set_has_playerjoin();
    _impl_.content_.playerjoin_ = playerjoin;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncRequest.playerJoin)
}
inline ::LobbyMessage::PlayerJoinRoomRequest* LobbySyncRequest::_internal_mutable_playerjoin() {
  if (!_internal_has_playerjoin()) {
    clear_content();
    set_has_playerjoin();
    _impl_.content_.playerjoin_ = CreateMaybeMessage< ::LobbyMessage::PlayerJoinRoomRequest >(GetArenaForAllocation());
  }
  return _impl_.content_.playerjoin_;
}
inline ::LobbyMessage::PlayerJoinRoomRequest* LobbySyncRequest::mutable_playerjoin() {
  ::LobbyMessage::PlayerJoinRoomRequest* _msg = _internal_mutable_playerjoin();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncRequest.playerJoin)
  return _msg;
}

// .LobbyMessage.PlayerPlayRoomRequest playerPlayRoom = 4;
inline bool LobbySyncRequest::_internal_has_playerplayroom() const {
  return content_case() == kPlayerPlayRoom;
}
inline bool LobbySyncRequest::has_playerplayroom() const {
  return _internal_has_playerplayroom();
}
inline void LobbySyncRequest::set_has_playerplayroom() {
  _impl_._oneof_case_[0] = kPlayerPlayRoom;
}
inline void LobbySyncRequest::clear_playerplayroom() {
  if (_internal_has_playerplayroom()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerplayroom_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerPlayRoomRequest* LobbySyncRequest::release_playerplayroom() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncRequest.playerPlayRoom)
  if (_internal_has_playerplayroom()) {
    clear_has_content();
    ::LobbyMessage::PlayerPlayRoomRequest* temp = _impl_.content_.playerplayroom_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerplayroom_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerPlayRoomRequest& LobbySyncRequest::_internal_playerplayroom() const {
  return _internal_has_playerplayroom()
      ? *_impl_.content_.playerplayroom_
      : reinterpret_cast< ::LobbyMessage::PlayerPlayRoomRequest&>(::LobbyMessage::_PlayerPlayRoomRequest_default_instance_);
}
inline const ::LobbyMessage::PlayerPlayRoomRequest& LobbySyncRequest::playerplayroom() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncRequest.playerPlayRoom)
  return _internal_playerplayroom();
}
inline ::LobbyMessage::PlayerPlayRoomRequest* LobbySyncRequest::unsafe_arena_release_playerplayroom() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncRequest.playerPlayRoom)
  if (_internal_has_playerplayroom()) {
    clear_has_content();
    ::LobbyMessage::PlayerPlayRoomRequest* temp = _impl_.content_.playerplayroom_;
    _impl_.content_.playerplayroom_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncRequest::unsafe_arena_set_allocated_playerplayroom(::LobbyMessage::PlayerPlayRoomRequest* playerplayroom) {
  clear_content();
  if (playerplayroom) {
    set_has_playerplayroom();
    _impl_.content_.playerplayroom_ = playerplayroom;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncRequest.playerPlayRoom)
}
inline ::LobbyMessage::PlayerPlayRoomRequest* LobbySyncRequest::_internal_mutable_playerplayroom() {
  if (!_internal_has_playerplayroom()) {
    clear_content();
    set_has_playerplayroom();
    _impl_.content_.playerplayroom_ = CreateMaybeMessage< ::LobbyMessage::PlayerPlayRoomRequest >(GetArenaForAllocation());
  }
  return _impl_.content_.playerplayroom_;
}
inline ::LobbyMessage::PlayerPlayRoomRequest* LobbySyncRequest::mutable_playerplayroom() {
  ::LobbyMessage::PlayerPlayRoomRequest* _msg = _internal_mutable_playerplayroom();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncRequest.playerPlayRoom)
  return _msg;
}

inline bool LobbySyncRequest::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void LobbySyncRequest::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline LobbySyncRequest::ContentCase LobbySyncRequest::content_case() const {
  return LobbySyncRequest::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PlayerLoginRequest

// string name = 1;
inline void PlayerLoginRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PlayerLoginRequest::name() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.PlayerLoginRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerLoginRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:LobbyMessage.PlayerLoginRequest.name)
}
inline std::string* PlayerLoginRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.PlayerLoginRequest.name)
  return _s;
}
inline const std::string& PlayerLoginRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PlayerLoginRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerLoginRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerLoginRequest::release_name() {
  // @@protoc_insertion_point(field_release:LobbyMessage.PlayerLoginRequest.name)
  return _impl_.name_.Release();
}
inline void PlayerLoginRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:LobbyMessage.PlayerLoginRequest.name)
}

// -------------------------------------------------------------------

// PlayerJoinRoomRequest

// -------------------------------------------------------------------

// PlayerPlayRoomRequest

// uint64 roomId = 1;
inline void PlayerPlayRoomRequest::clear_roomid() {
  _impl_.roomid_ = uint64_t{0u};
}
inline uint64_t PlayerPlayRoomRequest::_internal_roomid() const {
  return _impl_.roomid_;
}
inline uint64_t PlayerPlayRoomRequest::roomid() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.PlayerPlayRoomRequest.roomId)
  return _internal_roomid();
}
inline void PlayerPlayRoomRequest::_internal_set_roomid(uint64_t value) {
  
  _impl_.roomid_ = value;
}
inline void PlayerPlayRoomRequest::set_roomid(uint64_t value) {
  _internal_set_roomid(value);
  // @@protoc_insertion_point(field_set:LobbyMessage.PlayerPlayRoomRequest.roomId)
}

// -------------------------------------------------------------------

// LobbySyncResponse

// .LobbyMessage.PlayerLoginResponse playerLogin = 1;
inline bool LobbySyncResponse::_internal_has_playerlogin() const {
  return content_case() == kPlayerLogin;
}
inline bool LobbySyncResponse::has_playerlogin() const {
  return _internal_has_playerlogin();
}
inline void LobbySyncResponse::set_has_playerlogin() {
  _impl_._oneof_case_[0] = kPlayerLogin;
}
inline void LobbySyncResponse::clear_playerlogin() {
  if (_internal_has_playerlogin()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerlogin_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerLoginResponse* LobbySyncResponse::release_playerlogin() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncResponse.playerLogin)
  if (_internal_has_playerlogin()) {
    clear_has_content();
    ::LobbyMessage::PlayerLoginResponse* temp = _impl_.content_.playerlogin_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerlogin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerLoginResponse& LobbySyncResponse::_internal_playerlogin() const {
  return _internal_has_playerlogin()
      ? *_impl_.content_.playerlogin_
      : reinterpret_cast< ::LobbyMessage::PlayerLoginResponse&>(::LobbyMessage::_PlayerLoginResponse_default_instance_);
}
inline const ::LobbyMessage::PlayerLoginResponse& LobbySyncResponse::playerlogin() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncResponse.playerLogin)
  return _internal_playerlogin();
}
inline ::LobbyMessage::PlayerLoginResponse* LobbySyncResponse::unsafe_arena_release_playerlogin() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncResponse.playerLogin)
  if (_internal_has_playerlogin()) {
    clear_has_content();
    ::LobbyMessage::PlayerLoginResponse* temp = _impl_.content_.playerlogin_;
    _impl_.content_.playerlogin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncResponse::unsafe_arena_set_allocated_playerlogin(::LobbyMessage::PlayerLoginResponse* playerlogin) {
  clear_content();
  if (playerlogin) {
    set_has_playerlogin();
    _impl_.content_.playerlogin_ = playerlogin;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncResponse.playerLogin)
}
inline ::LobbyMessage::PlayerLoginResponse* LobbySyncResponse::_internal_mutable_playerlogin() {
  if (!_internal_has_playerlogin()) {
    clear_content();
    set_has_playerlogin();
    _impl_.content_.playerlogin_ = CreateMaybeMessage< ::LobbyMessage::PlayerLoginResponse >(GetArenaForAllocation());
  }
  return _impl_.content_.playerlogin_;
}
inline ::LobbyMessage::PlayerLoginResponse* LobbySyncResponse::mutable_playerlogin() {
  ::LobbyMessage::PlayerLoginResponse* _msg = _internal_mutable_playerlogin();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncResponse.playerLogin)
  return _msg;
}

// .LobbyMessage.PlayerJoinRoomResponse playerJoin = 2;
inline bool LobbySyncResponse::_internal_has_playerjoin() const {
  return content_case() == kPlayerJoin;
}
inline bool LobbySyncResponse::has_playerjoin() const {
  return _internal_has_playerjoin();
}
inline void LobbySyncResponse::set_has_playerjoin() {
  _impl_._oneof_case_[0] = kPlayerJoin;
}
inline void LobbySyncResponse::clear_playerjoin() {
  if (_internal_has_playerjoin()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerjoin_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerJoinRoomResponse* LobbySyncResponse::release_playerjoin() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncResponse.playerJoin)
  if (_internal_has_playerjoin()) {
    clear_has_content();
    ::LobbyMessage::PlayerJoinRoomResponse* temp = _impl_.content_.playerjoin_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerjoin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerJoinRoomResponse& LobbySyncResponse::_internal_playerjoin() const {
  return _internal_has_playerjoin()
      ? *_impl_.content_.playerjoin_
      : reinterpret_cast< ::LobbyMessage::PlayerJoinRoomResponse&>(::LobbyMessage::_PlayerJoinRoomResponse_default_instance_);
}
inline const ::LobbyMessage::PlayerJoinRoomResponse& LobbySyncResponse::playerjoin() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncResponse.playerJoin)
  return _internal_playerjoin();
}
inline ::LobbyMessage::PlayerJoinRoomResponse* LobbySyncResponse::unsafe_arena_release_playerjoin() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncResponse.playerJoin)
  if (_internal_has_playerjoin()) {
    clear_has_content();
    ::LobbyMessage::PlayerJoinRoomResponse* temp = _impl_.content_.playerjoin_;
    _impl_.content_.playerjoin_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncResponse::unsafe_arena_set_allocated_playerjoin(::LobbyMessage::PlayerJoinRoomResponse* playerjoin) {
  clear_content();
  if (playerjoin) {
    set_has_playerjoin();
    _impl_.content_.playerjoin_ = playerjoin;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncResponse.playerJoin)
}
inline ::LobbyMessage::PlayerJoinRoomResponse* LobbySyncResponse::_internal_mutable_playerjoin() {
  if (!_internal_has_playerjoin()) {
    clear_content();
    set_has_playerjoin();
    _impl_.content_.playerjoin_ = CreateMaybeMessage< ::LobbyMessage::PlayerJoinRoomResponse >(GetArenaForAllocation());
  }
  return _impl_.content_.playerjoin_;
}
inline ::LobbyMessage::PlayerJoinRoomResponse* LobbySyncResponse::mutable_playerjoin() {
  ::LobbyMessage::PlayerJoinRoomResponse* _msg = _internal_mutable_playerjoin();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncResponse.playerJoin)
  return _msg;
}

// .LobbyMessage.PlayerPlayRoomResponse playerPlayRoom = 3;
inline bool LobbySyncResponse::_internal_has_playerplayroom() const {
  return content_case() == kPlayerPlayRoom;
}
inline bool LobbySyncResponse::has_playerplayroom() const {
  return _internal_has_playerplayroom();
}
inline void LobbySyncResponse::set_has_playerplayroom() {
  _impl_._oneof_case_[0] = kPlayerPlayRoom;
}
inline void LobbySyncResponse::clear_playerplayroom() {
  if (_internal_has_playerplayroom()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.playerplayroom_;
    }
    clear_has_content();
  }
}
inline ::LobbyMessage::PlayerPlayRoomResponse* LobbySyncResponse::release_playerplayroom() {
  // @@protoc_insertion_point(field_release:LobbyMessage.LobbySyncResponse.playerPlayRoom)
  if (_internal_has_playerplayroom()) {
    clear_has_content();
    ::LobbyMessage::PlayerPlayRoomResponse* temp = _impl_.content_.playerplayroom_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.playerplayroom_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbyMessage::PlayerPlayRoomResponse& LobbySyncResponse::_internal_playerplayroom() const {
  return _internal_has_playerplayroom()
      ? *_impl_.content_.playerplayroom_
      : reinterpret_cast< ::LobbyMessage::PlayerPlayRoomResponse&>(::LobbyMessage::_PlayerPlayRoomResponse_default_instance_);
}
inline const ::LobbyMessage::PlayerPlayRoomResponse& LobbySyncResponse::playerplayroom() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.LobbySyncResponse.playerPlayRoom)
  return _internal_playerplayroom();
}
inline ::LobbyMessage::PlayerPlayRoomResponse* LobbySyncResponse::unsafe_arena_release_playerplayroom() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LobbyMessage.LobbySyncResponse.playerPlayRoom)
  if (_internal_has_playerplayroom()) {
    clear_has_content();
    ::LobbyMessage::PlayerPlayRoomResponse* temp = _impl_.content_.playerplayroom_;
    _impl_.content_.playerplayroom_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void LobbySyncResponse::unsafe_arena_set_allocated_playerplayroom(::LobbyMessage::PlayerPlayRoomResponse* playerplayroom) {
  clear_content();
  if (playerplayroom) {
    set_has_playerplayroom();
    _impl_.content_.playerplayroom_ = playerplayroom;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LobbyMessage.LobbySyncResponse.playerPlayRoom)
}
inline ::LobbyMessage::PlayerPlayRoomResponse* LobbySyncResponse::_internal_mutable_playerplayroom() {
  if (!_internal_has_playerplayroom()) {
    clear_content();
    set_has_playerplayroom();
    _impl_.content_.playerplayroom_ = CreateMaybeMessage< ::LobbyMessage::PlayerPlayRoomResponse >(GetArenaForAllocation());
  }
  return _impl_.content_.playerplayroom_;
}
inline ::LobbyMessage::PlayerPlayRoomResponse* LobbySyncResponse::mutable_playerplayroom() {
  ::LobbyMessage::PlayerPlayRoomResponse* _msg = _internal_mutable_playerplayroom();
  // @@protoc_insertion_point(field_mutable:LobbyMessage.LobbySyncResponse.playerPlayRoom)
  return _msg;
}

inline bool LobbySyncResponse::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void LobbySyncResponse::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline LobbySyncResponse::ContentCase LobbySyncResponse::content_case() const {
  return LobbySyncResponse::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PlayerLoginResponse

// uint64 playerId = 1;
inline void PlayerLoginResponse::clear_playerid() {
  _impl_.playerid_ = uint64_t{0u};
}
inline uint64_t PlayerLoginResponse::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint64_t PlayerLoginResponse::playerid() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.PlayerLoginResponse.playerId)
  return _internal_playerid();
}
inline void PlayerLoginResponse::_internal_set_playerid(uint64_t value) {
  
  _impl_.playerid_ = value;
}
inline void PlayerLoginResponse::set_playerid(uint64_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:LobbyMessage.PlayerLoginResponse.playerId)
}

// -------------------------------------------------------------------

// PlayerJoinRoomResponse

// uint64 roomId = 1;
inline void PlayerJoinRoomResponse::clear_roomid() {
  _impl_.roomid_ = uint64_t{0u};
}
inline uint64_t PlayerJoinRoomResponse::_internal_roomid() const {
  return _impl_.roomid_;
}
inline uint64_t PlayerJoinRoomResponse::roomid() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.PlayerJoinRoomResponse.roomId)
  return _internal_roomid();
}
inline void PlayerJoinRoomResponse::_internal_set_roomid(uint64_t value) {
  
  _impl_.roomid_ = value;
}
inline void PlayerJoinRoomResponse::set_roomid(uint64_t value) {
  _internal_set_roomid(value);
  // @@protoc_insertion_point(field_set:LobbyMessage.PlayerJoinRoomResponse.roomId)
}

// -------------------------------------------------------------------

// PlayerPlayRoomResponse

// uint64 roomId = 1;
inline void PlayerPlayRoomResponse::clear_roomid() {
  _impl_.roomid_ = uint64_t{0u};
}
inline uint64_t PlayerPlayRoomResponse::_internal_roomid() const {
  return _impl_.roomid_;
}
inline uint64_t PlayerPlayRoomResponse::roomid() const {
  // @@protoc_insertion_point(field_get:LobbyMessage.PlayerPlayRoomResponse.roomId)
  return _internal_roomid();
}
inline void PlayerPlayRoomResponse::_internal_set_roomid(uint64_t value) {
  
  _impl_.roomid_ = value;
}
inline void PlayerPlayRoomResponse::set_roomid(uint64_t value) {
  _internal_set_roomid(value);
  // @@protoc_insertion_point(field_set:LobbyMessage.PlayerPlayRoomResponse.roomId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LobbyMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_LobbyMessage_2eproto
