// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SyncMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SyncMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ConnectMessage.pb.h"
#include "GameMessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SyncMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SyncMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SyncMessage_2eproto;
namespace SyncMessage {
class ClientMessage;
struct ClientMessageDefaultTypeInternal;
extern ClientMessageDefaultTypeInternal _ClientMessage_default_instance_;
class ServerMessage;
struct ServerMessageDefaultTypeInternal;
extern ServerMessageDefaultTypeInternal _ServerMessage_default_instance_;
}  // namespace SyncMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::SyncMessage::ClientMessage* Arena::CreateMaybeMessage<::SyncMessage::ClientMessage>(Arena*);
template<> ::SyncMessage::ServerMessage* Arena::CreateMaybeMessage<::SyncMessage::ServerMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SyncMessage {

// ===================================================================

class ServerMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncMessage.ServerMessage) */ {
 public:
  inline ServerMessage() : ServerMessage(nullptr) {}
  ~ServerMessage() override;
  explicit PROTOBUF_CONSTEXPR ServerMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerMessage(const ServerMessage& from);
  ServerMessage(ServerMessage&& from) noexcept
    : ServerMessage() {
    *this = ::std::move(from);
  }

  inline ServerMessage& operator=(const ServerMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerMessage& operator=(ServerMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerMessage& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kCommonMessage = 2,
    kConnectMessage = 3,
    kGameSyncMessage = 4,
    CONTENT_NOT_SET = 0,
  };

  static inline const ServerMessage* internal_default_instance() {
    return reinterpret_cast<const ServerMessage*>(
               &_ServerMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerMessage& a, ServerMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerMessage& from) {
    ServerMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncMessage.ServerMessage";
  }
  protected:
  explicit ServerMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommonMessageFieldNumber = 2,
    kConnectMessageFieldNumber = 3,
    kGameSyncMessageFieldNumber = 4,
  };
  // string commonMessage = 2;
  bool has_commonmessage() const;
  private:
  bool _internal_has_commonmessage() const;
  public:
  void clear_commonmessage();
  const std::string& commonmessage() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_commonmessage(ArgT0&& arg0, ArgT... args);
  std::string* mutable_commonmessage();
  PROTOBUF_NODISCARD std::string* release_commonmessage();
  void set_allocated_commonmessage(std::string* commonmessage);
  private:
  const std::string& _internal_commonmessage() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_commonmessage(const std::string& value);
  std::string* _internal_mutable_commonmessage();
  public:

  // .ConnectMessage.ServerConnectMessage connectMessage = 3;
  bool has_connectmessage() const;
  private:
  bool _internal_has_connectmessage() const;
  public:
  void clear_connectmessage();
  const ::ConnectMessage::ServerConnectMessage& connectmessage() const;
  PROTOBUF_NODISCARD ::ConnectMessage::ServerConnectMessage* release_connectmessage();
  ::ConnectMessage::ServerConnectMessage* mutable_connectmessage();
  void set_allocated_connectmessage(::ConnectMessage::ServerConnectMessage* connectmessage);
  private:
  const ::ConnectMessage::ServerConnectMessage& _internal_connectmessage() const;
  ::ConnectMessage::ServerConnectMessage* _internal_mutable_connectmessage();
  public:
  void unsafe_arena_set_allocated_connectmessage(
      ::ConnectMessage::ServerConnectMessage* connectmessage);
  ::ConnectMessage::ServerConnectMessage* unsafe_arena_release_connectmessage();

  // .GameMessage.GameSyncMessage gameSyncMessage = 4;
  bool has_gamesyncmessage() const;
  private:
  bool _internal_has_gamesyncmessage() const;
  public:
  void clear_gamesyncmessage();
  const ::GameMessage::GameSyncMessage& gamesyncmessage() const;
  PROTOBUF_NODISCARD ::GameMessage::GameSyncMessage* release_gamesyncmessage();
  ::GameMessage::GameSyncMessage* mutable_gamesyncmessage();
  void set_allocated_gamesyncmessage(::GameMessage::GameSyncMessage* gamesyncmessage);
  private:
  const ::GameMessage::GameSyncMessage& _internal_gamesyncmessage() const;
  ::GameMessage::GameSyncMessage* _internal_mutable_gamesyncmessage();
  public:
  void unsafe_arena_set_allocated_gamesyncmessage(
      ::GameMessage::GameSyncMessage* gamesyncmessage);
  ::GameMessage::GameSyncMessage* unsafe_arena_release_gamesyncmessage();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:SyncMessage.ServerMessage)
 private:
  class _Internal;
  void set_has_commonmessage();
  void set_has_connectmessage();
  void set_has_gamesyncmessage();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr commonmessage_;
      ::ConnectMessage::ServerConnectMessage* connectmessage_;
      ::GameMessage::GameSyncMessage* gamesyncmessage_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SyncMessage_2eproto;
};
// -------------------------------------------------------------------

class ClientMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncMessage.ClientMessage) */ {
 public:
  inline ClientMessage() : ClientMessage(nullptr) {}
  ~ClientMessage() override;
  explicit PROTOBUF_CONSTEXPR ClientMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientMessage(const ClientMessage& from);
  ClientMessage(ClientMessage&& from) noexcept
    : ClientMessage() {
    *this = ::std::move(from);
  }

  inline ClientMessage& operator=(const ClientMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMessage& operator=(ClientMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientMessage& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kCommonMessage = 2,
    kConnectMessage = 3,
    kGameSyncMessage = 4,
    CONTENT_NOT_SET = 0,
  };

  static inline const ClientMessage* internal_default_instance() {
    return reinterpret_cast<const ClientMessage*>(
               &_ClientMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClientMessage& a, ClientMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientMessage& from) {
    ClientMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncMessage.ClientMessage";
  }
  protected:
  explicit ClientMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kCommonMessageFieldNumber = 2,
    kConnectMessageFieldNumber = 3,
    kGameSyncMessageFieldNumber = 4,
  };
  // uint64 clientId = 1;
  void clear_clientid();
  uint64_t clientid() const;
  void set_clientid(uint64_t value);
  private:
  uint64_t _internal_clientid() const;
  void _internal_set_clientid(uint64_t value);
  public:

  // string commonMessage = 2;
  bool has_commonmessage() const;
  private:
  bool _internal_has_commonmessage() const;
  public:
  void clear_commonmessage();
  const std::string& commonmessage() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_commonmessage(ArgT0&& arg0, ArgT... args);
  std::string* mutable_commonmessage();
  PROTOBUF_NODISCARD std::string* release_commonmessage();
  void set_allocated_commonmessage(std::string* commonmessage);
  private:
  const std::string& _internal_commonmessage() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_commonmessage(const std::string& value);
  std::string* _internal_mutable_commonmessage();
  public:

  // .ConnectMessage.ClientConnectMessage connectMessage = 3;
  bool has_connectmessage() const;
  private:
  bool _internal_has_connectmessage() const;
  public:
  void clear_connectmessage();
  const ::ConnectMessage::ClientConnectMessage& connectmessage() const;
  PROTOBUF_NODISCARD ::ConnectMessage::ClientConnectMessage* release_connectmessage();
  ::ConnectMessage::ClientConnectMessage* mutable_connectmessage();
  void set_allocated_connectmessage(::ConnectMessage::ClientConnectMessage* connectmessage);
  private:
  const ::ConnectMessage::ClientConnectMessage& _internal_connectmessage() const;
  ::ConnectMessage::ClientConnectMessage* _internal_mutable_connectmessage();
  public:
  void unsafe_arena_set_allocated_connectmessage(
      ::ConnectMessage::ClientConnectMessage* connectmessage);
  ::ConnectMessage::ClientConnectMessage* unsafe_arena_release_connectmessage();

  // .GameMessage.GameSyncMessage gameSyncMessage = 4;
  bool has_gamesyncmessage() const;
  private:
  bool _internal_has_gamesyncmessage() const;
  public:
  void clear_gamesyncmessage();
  const ::GameMessage::GameSyncMessage& gamesyncmessage() const;
  PROTOBUF_NODISCARD ::GameMessage::GameSyncMessage* release_gamesyncmessage();
  ::GameMessage::GameSyncMessage* mutable_gamesyncmessage();
  void set_allocated_gamesyncmessage(::GameMessage::GameSyncMessage* gamesyncmessage);
  private:
  const ::GameMessage::GameSyncMessage& _internal_gamesyncmessage() const;
  ::GameMessage::GameSyncMessage* _internal_mutable_gamesyncmessage();
  public:
  void unsafe_arena_set_allocated_gamesyncmessage(
      ::GameMessage::GameSyncMessage* gamesyncmessage);
  ::GameMessage::GameSyncMessage* unsafe_arena_release_gamesyncmessage();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:SyncMessage.ClientMessage)
 private:
  class _Internal;
  void set_has_commonmessage();
  void set_has_connectmessage();
  void set_has_gamesyncmessage();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t clientid_;
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr commonmessage_;
      ::ConnectMessage::ClientConnectMessage* connectmessage_;
      ::GameMessage::GameSyncMessage* gamesyncmessage_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SyncMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerMessage

// string commonMessage = 2;
inline bool ServerMessage::_internal_has_commonmessage() const {
  return content_case() == kCommonMessage;
}
inline bool ServerMessage::has_commonmessage() const {
  return _internal_has_commonmessage();
}
inline void ServerMessage::set_has_commonmessage() {
  _impl_._oneof_case_[0] = kCommonMessage;
}
inline void ServerMessage::clear_commonmessage() {
  if (_internal_has_commonmessage()) {
    _impl_.content_.commonmessage_.Destroy();
    clear_has_content();
  }
}
inline const std::string& ServerMessage::commonmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ServerMessage.commonMessage)
  return _internal_commonmessage();
}
template <typename ArgT0, typename... ArgT>
inline void ServerMessage::set_commonmessage(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  _impl_.content_.commonmessage_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncMessage.ServerMessage.commonMessage)
}
inline std::string* ServerMessage::mutable_commonmessage() {
  std::string* _s = _internal_mutable_commonmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ServerMessage.commonMessage)
  return _s;
}
inline const std::string& ServerMessage::_internal_commonmessage() const {
  if (_internal_has_commonmessage()) {
    return _impl_.content_.commonmessage_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ServerMessage::_internal_set_commonmessage(const std::string& value) {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  _impl_.content_.commonmessage_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerMessage::_internal_mutable_commonmessage() {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  return _impl_.content_.commonmessage_.Mutable(      GetArenaForAllocation());
}
inline std::string* ServerMessage::release_commonmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ServerMessage.commonMessage)
  if (_internal_has_commonmessage()) {
    clear_has_content();
    return _impl_.content_.commonmessage_.Release();
  } else {
    return nullptr;
  }
}
inline void ServerMessage::set_allocated_commonmessage(std::string* commonmessage) {
  if (has_content()) {
    clear_content();
  }
  if (commonmessage != nullptr) {
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitAllocated(commonmessage, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:SyncMessage.ServerMessage.commonMessage)
}

// .ConnectMessage.ServerConnectMessage connectMessage = 3;
inline bool ServerMessage::_internal_has_connectmessage() const {
  return content_case() == kConnectMessage;
}
inline bool ServerMessage::has_connectmessage() const {
  return _internal_has_connectmessage();
}
inline void ServerMessage::set_has_connectmessage() {
  _impl_._oneof_case_[0] = kConnectMessage;
}
inline ::ConnectMessage::ServerConnectMessage* ServerMessage::release_connectmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ServerMessage.connectMessage)
  if (_internal_has_connectmessage()) {
    clear_has_content();
    ::ConnectMessage::ServerConnectMessage* temp = _impl_.content_.connectmessage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.connectmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ConnectMessage::ServerConnectMessage& ServerMessage::_internal_connectmessage() const {
  return _internal_has_connectmessage()
      ? *_impl_.content_.connectmessage_
      : reinterpret_cast< ::ConnectMessage::ServerConnectMessage&>(::ConnectMessage::_ServerConnectMessage_default_instance_);
}
inline const ::ConnectMessage::ServerConnectMessage& ServerMessage::connectmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ServerMessage.connectMessage)
  return _internal_connectmessage();
}
inline ::ConnectMessage::ServerConnectMessage* ServerMessage::unsafe_arena_release_connectmessage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncMessage.ServerMessage.connectMessage)
  if (_internal_has_connectmessage()) {
    clear_has_content();
    ::ConnectMessage::ServerConnectMessage* temp = _impl_.content_.connectmessage_;
    _impl_.content_.connectmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ServerMessage::unsafe_arena_set_allocated_connectmessage(::ConnectMessage::ServerConnectMessage* connectmessage) {
  clear_content();
  if (connectmessage) {
    set_has_connectmessage();
    _impl_.content_.connectmessage_ = connectmessage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncMessage.ServerMessage.connectMessage)
}
inline ::ConnectMessage::ServerConnectMessage* ServerMessage::_internal_mutable_connectmessage() {
  if (!_internal_has_connectmessage()) {
    clear_content();
    set_has_connectmessage();
    _impl_.content_.connectmessage_ = CreateMaybeMessage< ::ConnectMessage::ServerConnectMessage >(GetArenaForAllocation());
  }
  return _impl_.content_.connectmessage_;
}
inline ::ConnectMessage::ServerConnectMessage* ServerMessage::mutable_connectmessage() {
  ::ConnectMessage::ServerConnectMessage* _msg = _internal_mutable_connectmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ServerMessage.connectMessage)
  return _msg;
}

// .GameMessage.GameSyncMessage gameSyncMessage = 4;
inline bool ServerMessage::_internal_has_gamesyncmessage() const {
  return content_case() == kGameSyncMessage;
}
inline bool ServerMessage::has_gamesyncmessage() const {
  return _internal_has_gamesyncmessage();
}
inline void ServerMessage::set_has_gamesyncmessage() {
  _impl_._oneof_case_[0] = kGameSyncMessage;
}
inline ::GameMessage::GameSyncMessage* ServerMessage::release_gamesyncmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ServerMessage.gameSyncMessage)
  if (_internal_has_gamesyncmessage()) {
    clear_has_content();
    ::GameMessage::GameSyncMessage* temp = _impl_.content_.gamesyncmessage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.gamesyncmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GameMessage::GameSyncMessage& ServerMessage::_internal_gamesyncmessage() const {
  return _internal_has_gamesyncmessage()
      ? *_impl_.content_.gamesyncmessage_
      : reinterpret_cast< ::GameMessage::GameSyncMessage&>(::GameMessage::_GameSyncMessage_default_instance_);
}
inline const ::GameMessage::GameSyncMessage& ServerMessage::gamesyncmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ServerMessage.gameSyncMessage)
  return _internal_gamesyncmessage();
}
inline ::GameMessage::GameSyncMessage* ServerMessage::unsafe_arena_release_gamesyncmessage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncMessage.ServerMessage.gameSyncMessage)
  if (_internal_has_gamesyncmessage()) {
    clear_has_content();
    ::GameMessage::GameSyncMessage* temp = _impl_.content_.gamesyncmessage_;
    _impl_.content_.gamesyncmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ServerMessage::unsafe_arena_set_allocated_gamesyncmessage(::GameMessage::GameSyncMessage* gamesyncmessage) {
  clear_content();
  if (gamesyncmessage) {
    set_has_gamesyncmessage();
    _impl_.content_.gamesyncmessage_ = gamesyncmessage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncMessage.ServerMessage.gameSyncMessage)
}
inline ::GameMessage::GameSyncMessage* ServerMessage::_internal_mutable_gamesyncmessage() {
  if (!_internal_has_gamesyncmessage()) {
    clear_content();
    set_has_gamesyncmessage();
    _impl_.content_.gamesyncmessage_ = CreateMaybeMessage< ::GameMessage::GameSyncMessage >(GetArenaForAllocation());
  }
  return _impl_.content_.gamesyncmessage_;
}
inline ::GameMessage::GameSyncMessage* ServerMessage::mutable_gamesyncmessage() {
  ::GameMessage::GameSyncMessage* _msg = _internal_mutable_gamesyncmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ServerMessage.gameSyncMessage)
  return _msg;
}

inline bool ServerMessage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void ServerMessage::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline ServerMessage::ContentCase ServerMessage::content_case() const {
  return ServerMessage::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ClientMessage

// uint64 clientId = 1;
inline void ClientMessage::clear_clientid() {
  _impl_.clientid_ = uint64_t{0u};
}
inline uint64_t ClientMessage::_internal_clientid() const {
  return _impl_.clientid_;
}
inline uint64_t ClientMessage::clientid() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ClientMessage.clientId)
  return _internal_clientid();
}
inline void ClientMessage::_internal_set_clientid(uint64_t value) {
  
  _impl_.clientid_ = value;
}
inline void ClientMessage::set_clientid(uint64_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:SyncMessage.ClientMessage.clientId)
}

// string commonMessage = 2;
inline bool ClientMessage::_internal_has_commonmessage() const {
  return content_case() == kCommonMessage;
}
inline bool ClientMessage::has_commonmessage() const {
  return _internal_has_commonmessage();
}
inline void ClientMessage::set_has_commonmessage() {
  _impl_._oneof_case_[0] = kCommonMessage;
}
inline void ClientMessage::clear_commonmessage() {
  if (_internal_has_commonmessage()) {
    _impl_.content_.commonmessage_.Destroy();
    clear_has_content();
  }
}
inline const std::string& ClientMessage::commonmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ClientMessage.commonMessage)
  return _internal_commonmessage();
}
template <typename ArgT0, typename... ArgT>
inline void ClientMessage::set_commonmessage(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  _impl_.content_.commonmessage_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncMessage.ClientMessage.commonMessage)
}
inline std::string* ClientMessage::mutable_commonmessage() {
  std::string* _s = _internal_mutable_commonmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ClientMessage.commonMessage)
  return _s;
}
inline const std::string& ClientMessage::_internal_commonmessage() const {
  if (_internal_has_commonmessage()) {
    return _impl_.content_.commonmessage_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ClientMessage::_internal_set_commonmessage(const std::string& value) {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  _impl_.content_.commonmessage_.Set(value, GetArenaForAllocation());
}
inline std::string* ClientMessage::_internal_mutable_commonmessage() {
  if (!_internal_has_commonmessage()) {
    clear_content();
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitDefault();
  }
  return _impl_.content_.commonmessage_.Mutable(      GetArenaForAllocation());
}
inline std::string* ClientMessage::release_commonmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ClientMessage.commonMessage)
  if (_internal_has_commonmessage()) {
    clear_has_content();
    return _impl_.content_.commonmessage_.Release();
  } else {
    return nullptr;
  }
}
inline void ClientMessage::set_allocated_commonmessage(std::string* commonmessage) {
  if (has_content()) {
    clear_content();
  }
  if (commonmessage != nullptr) {
    set_has_commonmessage();
    _impl_.content_.commonmessage_.InitAllocated(commonmessage, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:SyncMessage.ClientMessage.commonMessage)
}

// .ConnectMessage.ClientConnectMessage connectMessage = 3;
inline bool ClientMessage::_internal_has_connectmessage() const {
  return content_case() == kConnectMessage;
}
inline bool ClientMessage::has_connectmessage() const {
  return _internal_has_connectmessage();
}
inline void ClientMessage::set_has_connectmessage() {
  _impl_._oneof_case_[0] = kConnectMessage;
}
inline ::ConnectMessage::ClientConnectMessage* ClientMessage::release_connectmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ClientMessage.connectMessage)
  if (_internal_has_connectmessage()) {
    clear_has_content();
    ::ConnectMessage::ClientConnectMessage* temp = _impl_.content_.connectmessage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.connectmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ConnectMessage::ClientConnectMessage& ClientMessage::_internal_connectmessage() const {
  return _internal_has_connectmessage()
      ? *_impl_.content_.connectmessage_
      : reinterpret_cast< ::ConnectMessage::ClientConnectMessage&>(::ConnectMessage::_ClientConnectMessage_default_instance_);
}
inline const ::ConnectMessage::ClientConnectMessage& ClientMessage::connectmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ClientMessage.connectMessage)
  return _internal_connectmessage();
}
inline ::ConnectMessage::ClientConnectMessage* ClientMessage::unsafe_arena_release_connectmessage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncMessage.ClientMessage.connectMessage)
  if (_internal_has_connectmessage()) {
    clear_has_content();
    ::ConnectMessage::ClientConnectMessage* temp = _impl_.content_.connectmessage_;
    _impl_.content_.connectmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_connectmessage(::ConnectMessage::ClientConnectMessage* connectmessage) {
  clear_content();
  if (connectmessage) {
    set_has_connectmessage();
    _impl_.content_.connectmessage_ = connectmessage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncMessage.ClientMessage.connectMessage)
}
inline ::ConnectMessage::ClientConnectMessage* ClientMessage::_internal_mutable_connectmessage() {
  if (!_internal_has_connectmessage()) {
    clear_content();
    set_has_connectmessage();
    _impl_.content_.connectmessage_ = CreateMaybeMessage< ::ConnectMessage::ClientConnectMessage >(GetArenaForAllocation());
  }
  return _impl_.content_.connectmessage_;
}
inline ::ConnectMessage::ClientConnectMessage* ClientMessage::mutable_connectmessage() {
  ::ConnectMessage::ClientConnectMessage* _msg = _internal_mutable_connectmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ClientMessage.connectMessage)
  return _msg;
}

// .GameMessage.GameSyncMessage gameSyncMessage = 4;
inline bool ClientMessage::_internal_has_gamesyncmessage() const {
  return content_case() == kGameSyncMessage;
}
inline bool ClientMessage::has_gamesyncmessage() const {
  return _internal_has_gamesyncmessage();
}
inline void ClientMessage::set_has_gamesyncmessage() {
  _impl_._oneof_case_[0] = kGameSyncMessage;
}
inline ::GameMessage::GameSyncMessage* ClientMessage::release_gamesyncmessage() {
  // @@protoc_insertion_point(field_release:SyncMessage.ClientMessage.gameSyncMessage)
  if (_internal_has_gamesyncmessage()) {
    clear_has_content();
    ::GameMessage::GameSyncMessage* temp = _impl_.content_.gamesyncmessage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.gamesyncmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GameMessage::GameSyncMessage& ClientMessage::_internal_gamesyncmessage() const {
  return _internal_has_gamesyncmessage()
      ? *_impl_.content_.gamesyncmessage_
      : reinterpret_cast< ::GameMessage::GameSyncMessage&>(::GameMessage::_GameSyncMessage_default_instance_);
}
inline const ::GameMessage::GameSyncMessage& ClientMessage::gamesyncmessage() const {
  // @@protoc_insertion_point(field_get:SyncMessage.ClientMessage.gameSyncMessage)
  return _internal_gamesyncmessage();
}
inline ::GameMessage::GameSyncMessage* ClientMessage::unsafe_arena_release_gamesyncmessage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncMessage.ClientMessage.gameSyncMessage)
  if (_internal_has_gamesyncmessage()) {
    clear_has_content();
    ::GameMessage::GameSyncMessage* temp = _impl_.content_.gamesyncmessage_;
    _impl_.content_.gamesyncmessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_gamesyncmessage(::GameMessage::GameSyncMessage* gamesyncmessage) {
  clear_content();
  if (gamesyncmessage) {
    set_has_gamesyncmessage();
    _impl_.content_.gamesyncmessage_ = gamesyncmessage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncMessage.ClientMessage.gameSyncMessage)
}
inline ::GameMessage::GameSyncMessage* ClientMessage::_internal_mutable_gamesyncmessage() {
  if (!_internal_has_gamesyncmessage()) {
    clear_content();
    set_has_gamesyncmessage();
    _impl_.content_.gamesyncmessage_ = CreateMaybeMessage< ::GameMessage::GameSyncMessage >(GetArenaForAllocation());
  }
  return _impl_.content_.gamesyncmessage_;
}
inline ::GameMessage::GameSyncMessage* ClientMessage::mutable_gamesyncmessage() {
  ::GameMessage::GameSyncMessage* _msg = _internal_mutable_gamesyncmessage();
  // @@protoc_insertion_point(field_mutable:SyncMessage.ClientMessage.gameSyncMessage)
  return _msg;
}

inline bool ClientMessage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void ClientMessage::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline ClientMessage::ContentCase ClientMessage::content_case() const {
  return ClientMessage::ContentCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SyncMessage_2eproto
